# Generated by Django 4.2.27 on 2026-01-11 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_pastita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do combo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('preco_original', models.DecimalField(blank=True, decimal_places=2, help_text='Preço sem desconto (para mostrar economia)', max_digits=8, null=True, verbose_name='Preço Original (R$)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='combos/', verbose_name='Imagem do combo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, help_text="Mostrar como 'Mais Pedido'", verbose_name='Destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Carne',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastita.produto')),
                ('tipo', models.CharField(choices=[('isca_file', 'Iscas de Filé'), ('frango_grelhado', 'Frango Grelhado'), ('carne_moida', 'Carne Moída'), ('linguica_calabresa', 'Linguiça Calabresa'), ('bacon', 'Bacon'), ('costela', 'Costela Desfiada'), ('picanha', 'Picanha')], max_length=30, verbose_name='Tipo de Carne')),
                ('quantidade', models.CharField(help_text='Ex.: 200g, 300g', max_length=50, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Carne',
                'verbose_name_plural': 'Carnes',
            },
            bases=('pastita.produto',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Pagamento MP')),
                ('preference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Preferência MP')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('pago', 'Pago'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('falhou', 'Falhou'), ('reembolsado', 'Reembolsado'), ('em_mediacao', 'Em Mediação'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (R$)')),
                ('endereco_entrega', models.TextField(blank=True, verbose_name='Endereço de Entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_pastita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Unitário (R$)')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pastita.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastita.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemComboPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_combo', models.CharField(max_length=100, verbose_name='Nome do Combo')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Unitário (R$)')),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastita.combo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='pastita.pedido')),
            ],
            options={
                'verbose_name': 'Combo do Pedido',
                'verbose_name_plural': 'Combos do Pedido',
            },
        ),
        migrations.CreateModel(
            name='Rondelli',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastita.produto')),
                ('categoria', models.CharField(choices=[('classicos', 'Clássicos'), ('gourmet', 'Gourmet')], default='classicos', help_text='Defina se este sabor é Clássico ou Gourmet', max_length=10, verbose_name='Categoria')),
                ('sabor', models.CharField(choices=[('presunto_e_queijo', 'Presunto e Queijo'), ('calabresa_com_requeijao', 'Calabresa com Requeijão'), ('frango_requeijao_mucarela', 'Frango, Requeijão e Muçarela'), ('linguica_toscana_erva_doce', 'Linguiça Toscana e Erva-Doce'), ('queijo_brocolis', 'Queijo e Brócolis'), ('tomate_seco_rucula', 'Tomate Seco com Rúcula'), ('4queijos', '4 Queijos'), ('queijos_manjericao', 'Queijos com Manjericão'), ('palmito', 'Palmito'), ('bacalhau_cremoso', 'Bacalhau Cremoso'), ('queijo_brie_damasco_castanha', 'Queijo Brie, Damasco e Castanha'), ('chambari_especiarias', 'Chambari com Especiarias'), ('camarao_catupiry', 'Camarão com Catupiry'), ('carne_seca_abobora', 'Carne Seca com Abóbora')], max_length=50, verbose_name='Sabor de Rondelli')),
                ('quantidade', models.CharField(help_text='Ex.: 500g, 1kg', max_length=50, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Rondelli',
                'verbose_name_plural': 'Rondellis',
                'unique_together': {('sabor', 'quantidade')},
            },
            bases=('pastita.produto',),
        ),
        migrations.CreateModel(
            name='Molho',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastita.produto')),
                ('tipo', models.CharField(choices=[('4queijos', '4 Queijos'), ('sugo', 'Sugo'), ('branco', 'Molho Branco'), ('pesto', 'Pesto'), ('bolonhesa', 'Bolonhesa'), ('carbonara', 'Carbonara')], max_length=20, verbose_name='Tipo de Molho')),
                ('quantidade', models.CharField(help_text='Ex.: 150g, 300g', max_length=50, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Molho',
                'verbose_name_plural': 'Molhos',
                'unique_together': {('tipo', 'quantidade')},
            },
            bases=('pastita.produto',),
        ),
        migrations.CreateModel(
            name='ItemComboCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='pastita.carrinho')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='pastita.combo')),
            ],
            options={
                'verbose_name': 'Combo no Carrinho',
                'verbose_name_plural': 'Combos no Carrinho',
                'unique_together': {('carrinho', 'combo')},
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pastita.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='pastita.produto')),
            ],
            options={
                'verbose_name': 'Item do Carrinho',
                'verbose_name_plural': 'Itens do Carrinho',
                'unique_together': {('carrinho', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='carne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='pastita.carne', verbose_name='Carne'),
        ),
        migrations.AddField(
            model_name='combo',
            name='molhos',
            field=models.ManyToManyField(blank=True, help_text='Selecione os molhos inclusos neste combo', related_name='combos', to='pastita.molho', verbose_name='Molhos inclusos'),
        ),
        migrations.AddField(
            model_name='combo',
            name='rondelli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='pastita.rondelli', verbose_name='Rondelli'),
        ),
        migrations.AddField(
            model_name='carne',
            name='molhos',
            field=models.ManyToManyField(blank=True, help_text='Selecione os molhos que podem acompanhar esta carne', related_name='carnes_compativeis', to='pastita.molho', verbose_name='Molhos disponíveis'),
        ),
        migrations.AlterUniqueTogether(
            name='carne',
            unique_together={('tipo', 'quantidade')},
        ),
    ]
