[databases]
pastita = host=db port=5432 user=postgres password=postgres123 dbname=pastita

[pgbouncer]
listen_port = 6432
listen_addr = 0.0.0.0
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 25
reserve_pool_size = 5
reserve_pool_timeout = 3
idle_in_transaction_session_timeout = 60000
server_idle_timeout = 600
server_connect_timeout = 15
server_login_retry_timeout = 15
client_idle_timeout = 900
query_wait_timeout = 120
autodb_idle_timeout = 60
application_name_add_host = 1
server_check_query = select 1

; Verbosity
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1
stats_period = 60
