# Generated by Django 4.2.28 on 2026-02-09 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('page_name', models.CharField(max_length=255)),
                ('page_access_token', models.TextField()),
                ('app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('app_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_verified', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('followers_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messenger Account',
                'verbose_name_plural': 'Messenger Accounts',
                'db_table': 'messenger_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messenger_conversation_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('psid', models.CharField(help_text='Page-scoped ID do usuário', max_length=255)),
                ('participant_name', models.CharField(blank=True, max_length=255)),
                ('participant_profile_pic', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messaging.messengeraccount')),
            ],
            options={
                'verbose_name': 'Messenger Conversation',
                'verbose_name_plural': 'Messenger Conversations',
                'db_table': 'messenger_conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messenger_webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerSponsoredMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ad_account_id', models.CharField(max_length=255)),
                ('message_type', models.CharField(default='TEXT', max_length=20)),
                ('content', models.TextField()),
                ('template_payload', models.JSONField(blank=True, default=dict)),
                ('targeting', models.JSONField(default=dict)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Em Revisão'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('ACTIVE', 'Ativo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Concluído')], default='DRAFT', max_length=20)),
                ('facebook_ad_id', models.CharField(blank=True, max_length=255, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_messages', to='messaging.messengeraccount')),
            ],
            options={
                'db_table': 'messenger_sponsored_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.TextField(blank=True, help_text='Mensagem de saudação inicial')),
                ('get_started_payload', models.CharField(blank=True, default='GET_STARTED', max_length=1000)),
                ('persistent_menu', models.JSONField(blank=True, default=dict)),
                ('ice_breakers', models.JSONField(blank=True, default=list)),
                ('whitelisted_domains', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='messaging.messengeraccount')),
            ],
            options={
                'db_table': 'messenger_profiles',
            },
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messenger_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('FILE', 'Arquivo'), ('STICKER', 'Sticker'), ('TEMPLATE', 'Template'), ('QUICK_REPLY', 'Resposta Rápida'), ('POSTBACK', 'Postback'), ('CALL', 'Chamada')], default='TEXT', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=50)),
                ('template_payload', models.JSONField(blank=True, default=dict)),
                ('quick_replies', models.JSONField(blank=True, default=list)),
                ('is_from_page', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.messengerconversation')),
            ],
            options={
                'verbose_name': 'Messenger Message',
                'verbose_name_plural': 'Messenger Messages',
                'db_table': 'messenger_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('extension_type', models.CharField(choices=[('CHAT_EXTENSION', 'Chat Extension'), ('GAME', 'Jogo'), ('WEBVIEW', 'Webview')], max_length=20)),
                ('url', models.URLField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('webview_height_ratio', models.CharField(choices=[('compact', 'Compacto'), ('tall', 'Alto'), ('full', 'Cheio')], default='tall', max_length=20)),
                ('in_test', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='messaging.messengeraccount')),
            ],
            options={
                'db_table': 'messenger_extensions',
            },
        ),
        migrations.CreateModel(
            name='MessengerBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('FILE', 'Arquivo'), ('STICKER', 'Sticker'), ('TEMPLATE', 'Template'), ('QUICK_REPLY', 'Resposta Rápida'), ('POSTBACK', 'Postback'), ('CALL', 'Chamada')], default='TEXT', max_length=20)),
                ('content', models.TextField()),
                ('template_payload', models.JSONField(blank=True, default=dict)),
                ('target_audience', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SCHEDULED', 'Agendado'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='DRAFT', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='messaging.messengeraccount')),
            ],
            options={
                'db_table': 'messenger_broadcasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
