# Generated by Django 4.2 on 2026-02-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0019_remove_storepaymentwebhookevent_store_pay_webhook_gateway_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(db_index=True, max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_status', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(default='api', help_text='Source: api, automation, campaign, webhook, manual', max_length=30)),
                ('source_id', models.CharField(blank=True, help_text='ID of the source object (campaign ID, automation ID, etc.)', max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='stores.store')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messaging_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('action', models.CharField(help_text='Action being performed', max_length=50)),
                ('description', models.TextField()),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'db_table': 'messaging_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('quiet_hours', 'Quiet Hours'), ('rate_limit', 'Rate Limit'), ('blacklist', 'Blacklist'), ('whitelist', 'Whitelist'), ('max_daily', 'Max Daily Messages')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Rule-specific configuration')),
                ('channels', models.JSONField(default=list, help_text="List of channels: ['whatsapp', 'email', 'sms']")),
                ('priority', models.IntegerField(default=100)),
                ('store', models.ForeignKey(blank=True, help_text='Global rules if null, store-specific if set', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_rules', to='stores.store')),
            ],
            options={
                'verbose_name': 'Message Rule',
                'verbose_name_plural': 'Message Rules',
                'db_table': 'messaging_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'Email'), ('sms', 'SMS'), ('universal', 'Universal')], default='universal', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject for email', max_length=255)),
                ('body', models.TextField(help_text='Template body with {variable} placeholders')),
                ('html_body', models.TextField(blank=True, help_text='HTML version for email')),
                ('media_url', models.URLField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=20)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=list, help_text="List of required variables: [{'name': 'customer_name', 'type': 'string', 'required': true}]")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('whatsapp_template_name', models.CharField(blank=True, help_text='Name of the approved template in WhatsApp Business API', max_length=255)),
                ('whatsapp_template_status', models.CharField(blank=True, help_text='APPROVED, REJECTED, PENDING', max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='Marketing, Utility, Authentication', max_length=50)),
                ('language', models.CharField(default='pt_BR', max_length=10)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='stores.store')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'db_table': 'messaging_templates',
                'ordering': ['store', 'name'],
                'unique_together': {('store', 'name', 'channel')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['store', 'channel', 'status'], name='messaging_m_store_id_5e8b30_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['store', 'recipient', '-created_at'], name='messaging_m_store_id_98f5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'scheduled_at'], name='messaging_m_status_5a2f50_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source', 'source_id'], name='messaging_m_source_b2e8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_id'], name='messaging_m_externa_7c9a95_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetemplate'),
        ),
    ]
