# Generated by Django 4.2 on 2026-02-02 05:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration - models already created.
    This satisfies Django's migration check without altering database.
    """

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
    ]
