# Generated by Django 5.2.15 on 2026-06-25 23:27

import apps.core.fields
from django.db import migrations


def encrypt_existing_tokens(apps, schema_editor):
    """Criptografa em repouso os segredos já gravados em texto plano.

    EncryptedCharField lê plaintext legado de forma transparente e
    re-criptografa no save — então basta resalvar cada linha. Idempotente:
    valores já criptografados (gAAA...) não são re-criptografados.
    """
    MessengerAccount = apps.get_model('messaging', 'MessengerAccount')
    for account in MessengerAccount.objects.all().iterator():
        account.save(update_fields=['page_access_token', 'app_secret'])


def noop_reverse(apps, schema_editor):
    # Não há reversão: não regravamos segredos em texto plano.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messengeraccount_default_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeraccount',
            name='app_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='page_access_token',
            field=apps.core.fields.EncryptedCharField(max_length=1000),
        ),
        migrations.RunPython(encrypt_existing_tokens, noop_reverse),
    ]
