# Generated by Django 4.2.29 on 2026-03-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_v2', '0001_initial'),
    ]

    operations = [
    ]
