# Generated by Django 4.2.29 on 2026-03-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_v2', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        # Adicionar campos do WhatsApp
        migrations.AddField(
            model_name='platformaccount',
            name='phone_number_id',
            field=models.CharField(max_length=50, blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='waba_id',
            field=models.CharField(max_length=50, blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='display_phone_number',
            field=models.CharField(max_length=30, blank=True),
        ),
        
        # Adicionar campos do Messenger
        migrations.AddField(
            model_name='platformaccount',
            name='page_id',
            field=models.CharField(max_length=255, blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='page_name',
            field=models.CharField(max_length=255, blank=True),
        ),
        
        # Adicionar campos do Instagram
        migrations.AddField(
            model_name='platformaccount',
            name='instagram_account_id',
            field=models.CharField(max_length=255, blank=True),
        ),
        
        # Adicionar campos comuns
        migrations.AddField(
            model_name='platformaccount',
            name='token_expires_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='status',
            field=models.CharField(max_length=20, default='pending'),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='webhook_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='webhook_verify_token',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='auto_response_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='human_handoff_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='default_agent_id',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='category',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='last_sync_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        
        # Tornar phone_number opcional
        migrations.AlterField(
            model_name='platformaccount',
            name='phone_number',
            field=models.CharField(max_length=20, blank=True),
        ),
        
        # Tornar access_token opcional
        migrations.AlterField(
            model_name='platformaccount',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        
        # Adicionar constraints de unicidade
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(
                fields=['created_by', 'platform', 'phone_number_id'],
                name='unique_whatsapp_account',
                condition=models.Q(platform='whatsapp', phone_number_id__gt='')
            ),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(
                fields=['created_by', 'platform', 'waba_id'],
                name='unique_waba',
                condition=models.Q(platform='whatsapp', waba_id__gt='')
            ),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(
                fields=['created_by', 'platform', 'page_id'],
                name='unique_messenger_page',
                condition=models.Q(platform='messenger', page_id__gt='')
            ),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(
                fields=['created_by', 'platform', 'instagram_account_id'],
                name='unique_instagram_account',
                condition=models.Q(platform='instagram', instagram_account_id__gt='')
            ),
        ),
    ]
