# Generated by Django 5.2.17 on 2026-08-28 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('whatsapp', '0009_alter_webhookevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='messages_opted_out',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignOptOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_key', models.CharField(db_index=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('origem', models.CharField(choices=[('button', 'Botão "Parar promoções"'), ('text', 'Escreveu pedindo para sair'), ('manual', 'Marcado pelo lojista')], default='button', max_length=20)),
                ('texto_recebido', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='whatsapp.whatsappaccount')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opt_outs', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_opt_outs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'revogado_em'], name='campaign_op_account_ab665c_idx')],
                'unique_together': {('account', 'phone_key')},
            },
        ),
    ]
