# Generated by Django 5.2.17 on 2026-09-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_messages_opted_out_campaignoptout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
