# Generated by Django 6.0 on 2026-01-03 22:36

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='products/'),
        ),
    ]
