# Generated by Django 6.0.6 on 2026-08-11 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0067_remetente_proprio_da_loja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('canonical_name', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('preparation_state', models.CharField(blank=True, max_length=80)),
                ('default_unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=4)),
                ('density_g_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('source', models.CharField(choices=[('taco', 'TACO/NEPA-Unicamp'), ('tbca', 'TBCA'), ('manufacturer', 'Fabricante'), ('lab', 'Laudo laboratorial'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('source_code', models.CharField(blank=True, max_length=80)),
                ('source_edition', models.CharField(blank=True, max_length=80)),
                ('source_reference', models.URLField(blank=True)),
                ('source_accessed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('carbohydrates_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_sugars_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('added_sugars_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_fat_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('trans_fat_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_ingredients', to='stores.store')),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='ProductNutritionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('value_source', models.CharField(choices=[('calculated', 'Calculado'), ('manual', 'Manual'), ('hybrid', 'Híbrido')], default='calculated', max_length=20)),
                ('serving_size_g', models.DecimalField(decimal_places=3, default=100, max_digits=10)),
                ('household_measure', models.CharField(blank=True, max_length=100)),
                ('manual_override_reason', models.TextField(blank=True)),
                ('is_print_approved', models.BooleanField(db_index=True, default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('carbohydrates_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_sugars_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('added_sugars_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_fat_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('trans_fat_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_profiles_approved', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to='stores.storeproduct')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionProfileRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='nutrition.productnutritionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('serving_size_g', models.DecimalField(decimal_places=3, default=100, max_digits=10)),
                ('household_measure', models.CharField(blank=True, max_length=100)),
                ('servings_per_container', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prepared_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('calculation_mode', models.CharField(choices=[('calculated', 'Calculado'), ('manual', 'Manual'), ('hybrid', 'Híbrido')], default='calculated', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('estimated', 'Estimado'), ('reviewed', 'Revisado'), ('approved', 'Aprovado')], default='draft', max_length=20)),
                ('source_notes', models.TextField(blank=True)),
                ('calculation_version', models.PositiveIntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_recipe', to='stores.storeproduct')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_recipes_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productnutritionprofile',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='nutrition.productrecipe'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity_g', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prepared_quantity_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('yield_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='nutrition.nutritioningredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.productrecipe')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='nutritioningredient',
            constraint=models.UniqueConstraint(fields=('store', 'canonical_name', 'preparation_state'), name='uniq_nutrition_ingredient_store_name_state'),
        ),
        migrations.AddConstraint(
            model_name='nutritioningredient',
            constraint=models.CheckConstraint(condition=models.Q(('density_g_ml__isnull', True), ('density_g_ml__gt', 0), _connector='OR'), name='nutrition_density_positive'),
        ),
        migrations.AddConstraint(
            model_name='nutritionprofilerevision',
            constraint=models.UniqueConstraint(fields=('profile', 'version'), name='uniq_nutrition_profile_revision'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='uniq_recipe_ingredient'),
        ),
    ]
