# Generated by Django 5.2.17 on 2026-08-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioningredient',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nutritioningredient',
            name='may_contain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productnutritionprofile',
            name='physical_form',
            field=models.CharField(choices=[('solido', 'Sólido'), ('liquido', 'Líquido')], default='solido', max_length=10),
        ),
    ]
