# Generated by Django 5.2.17 on 2026-08-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_nutritioningredient_allergens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioningredient',
            name='allergens_reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
