# Generated by Django 5.2.17 on 2026-08-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_nutritioningredient_allergens_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritioningredient',
            name='source',
            field=models.CharField(choices=[('taco', 'TACO/NEPA-Unicamp'), ('tbca', 'TBCA'), ('pof', 'POF/IBGE (Composição Nutricional)'), ('manufacturer', 'Fabricante'), ('lab', 'Laudo laboratorial'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
