# Generated by Django 5.2.17 on 2026-08-12 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_nutritioningredient_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioningredient',
            name='prepared_weight_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='IngredientComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity_g', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('composto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='nutrition.nutritioningredient')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_compostos', to='nutrition.nutritioningredient')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('composto', 'ingrediente'), name='uniq_componente_do_composto'), models.CheckConstraint(condition=models.Q(('composto', models.F('ingrediente')), _negated=True), name='componente_nao_e_ele_mesmo')],
            },
        ),
    ]
