# Generated by Django 5.2.17 on 2026-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_nutritioningredient_prepared_weight_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioningredient',
            name='lactose',
            field=models.CharField(choices=[('contem', 'Contém lactose'), ('baixo_teor', 'Baixo teor de lactose'), ('zero', 'Zero lactose'), ('isento', 'Não contém lactose'), ('nao_revisado', 'Não revisado')], db_index=True, default='nao_revisado', max_length=20),
        ),
    ]
