# Generated by Django 5.2.17 on 2026-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_nutritioningredient_lactose'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioningredient',
            name='preco_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritioningredient',
            name='quantidade_comprada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='nutritioningredient',
            name='quantidade_por_unidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritioningredient',
            name='unidade_compra',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('ml', 'ml'), ('un', 'unidade')], max_length=2),
        ),
    ]
