# Generated by Django 5.2.17 on 2026-09-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_custo_do_ingrediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritioningredient',
            name='source',
            field=models.CharField(choices=[('taco', 'TACO/NEPA-Unicamp'), ('tbca', 'TBCA'), ('pof', 'POF/IBGE (Composição Nutricional)'), ('manufacturer', 'Fabricante'), ('off', 'Open Food Facts (rótulo do fabricante)'), ('lab', 'Laudo laboratorial'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
