# Generated by Django 4.2.28 on 2026-03-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_delete_conversationhandover'),
        ('whatsapp', '0003_add_intent_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedtemplate',
            name='account',
        ),
        migrations.RemoveField(
            model_name='advancedtemplatelog',
            name='template',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='account',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flowresponse',
            name='flow',
        ),
        migrations.DeleteModel(
            name='MessageContext',
        ),
        migrations.AlterUniqueTogether(
            name='whatsappanalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='whatsappanalytics',
            name='account',
        ),
        migrations.RemoveField(
            model_name='whatsappanalyticsreport',
            name='accounts',
        ),
        migrations.RenameIndex(
            model_name='intentlog',
            new_name='whatsapp_in_account_7e9937_idx',
            old_name='whatsapp_in_account__bd0cf3_idx',
        ),
        migrations.RenameIndex(
            model_name='intentlog',
            new_name='whatsapp_in_intent__207b7b_idx',
            old_name='whatsapp_in_intent__3f4f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='intentlog',
            new_name='whatsapp_in_method_ea31ff_idx',
            old_name='whatsapp_in_method_8c5f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='intentlog',
            new_name='whatsapp_in_phone_n_e45310_idx',
            old_name='whatsapp_in_phone_n_8a5f9c_idx',
        ),
        migrations.AddField(
            model_name='intentlog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='intentlog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_intent_logs', to='whatsapp.whatsappaccount'),
        ),
        migrations.AlterField(
            model_name='intentlog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_intent_logs', to='conversations.conversation'),
        ),
        migrations.AlterField(
            model_name='intentlog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_intent_logs', to='whatsapp.message'),
        ),
        migrations.AddIndex(
            model_name='intentlog',
            index=models.Index(fields=['created_at'], name='whatsapp_in_created_4f3811_idx'),
        ),
        migrations.DeleteModel(
            name='AdvancedTemplate',
        ),
        migrations.DeleteModel(
            name='AdvancedTemplateLog',
        ),
        migrations.DeleteModel(
            name='Flow',
        ),
        migrations.DeleteModel(
            name='FlowResponse',
        ),
        migrations.DeleteModel(
            name='WhatsAppAnalytics',
        ),
        migrations.DeleteModel(
            name='WhatsAppAnalyticsReport',
        ),
    ]
