# Generated by Django 5.2.14 on 2026-05-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_messagecontext_state_and_field_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='template_class',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
    ]
