# Generated by Django 5.2.14 on 2026-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_add_template_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedtemplate',
            name='components',
            field=models.JSONField(default=list, verbose_name='Componentes'),
        ),
        migrations.AlterField(
            model_name='advancedtemplate',
            name='config',
            field=models.JSONField(default=dict, verbose_name='Configuração'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='flow_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Flow ID (Meta)'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='whatsappanalyticsreport',
            name='schedule_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dia do Agendamento'),
        ),
    ]
