# Generated by Django 5.2.15 on 2026-06-17 18:29
# Índices criados CONCURRENTLY: whatsapp_messages é a maior tabela; AddIndex normal
# travaria a tabela durante o CREATE INDEX. atomic=False é obrigatório p/ concurrent.
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('conversations', '0006_conversation_contact_profile_fields'),
        ('whatsapp', '0006_sync_template_fields_2026_05'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='message',
            index=models.Index(fields=['account', '-created_at'], name='wamsg_acct_created_idx'),
        ),
        AddIndexConcurrently(
            model_name='message',
            index=models.Index(fields=['account', 'direction', '-created_at'], name='wamsg_acct_dir_created_idx'),
        ),
    ]
