# Generated by Django 5.2.16 on 2026-08-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_message_wamsg_acct_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pipeline_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
