# Generated by Django 5.2.16 on 2026-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_message_pipeline_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(choices=[('message', 'Message'), ('status', 'Status Update'), ('error', 'Error'), ('account_update', 'Account Update'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
