# Generated by Django 5.2.17 on 2026-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_phone_cpf_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
