# Generated by Django 4.2.28 on 2026-02-19 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_requests', to='conversations.conversation', verbose_name='Conversa')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Handover',
                'verbose_name_plural': 'Solicitações de Handover',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('bot', 'Bot'), ('human', 'Human'), ('pending', 'Pendente')], max_length=20, verbose_name='De')),
                ('to_status', models.CharField(choices=[('bot', 'Bot'), ('human', 'Human'), ('pending', 'Pendente')], max_length=20, verbose_name='Para')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_logs_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_logs', to='conversations.conversation', verbose_name='Conversa')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_logs', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Log de Handover',
                'verbose_name_plural': 'Logs de Handover',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('bot', 'Bot'), ('human', 'Human'), ('pending', 'Pendente')], default='bot', max_length=20, verbose_name='Status')),
                ('last_transfer_at', models.DateTimeField(blank=True, null=True, verbose_name='Última transferência')),
                ('transfer_reason', models.TextField(blank=True, verbose_name='Motivo da transferência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handovers', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='conversations.conversation', verbose_name='Conversa')),
                ('last_transfer_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to=settings.AUTH_USER_MODEL, verbose_name='Transferido por')),
            ],
            options={
                'verbose_name': 'Controle de Handover',
                'verbose_name_plural': 'Controles de Handover',
                'ordering': ['-updated_at'],
            },
        ),
    ]
