# Generated by Django 5.2.17 on 2026-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationhandover',
            name='status',
            field=models.CharField(choices=[('bot', 'Bot'), ('human', 'Humano'), ('pending', 'Pendente')], default='bot', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='handoverlog',
            name='from_status',
            field=models.CharField(choices=[('bot', 'Bot'), ('human', 'Humano'), ('pending', 'Pendente')], max_length=20, verbose_name='De'),
        ),
        migrations.AlterField(
            model_name='handoverlog',
            name='to_status',
            field=models.CharField(choices=[('bot', 'Bot'), ('human', 'Humano'), ('pending', 'Pendente')], max_length=20, verbose_name='Para'),
        ),
    ]
