# Generated by Django 5.2.10 on 2026-01-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cash', 'Dinheiro'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet'), ('other', 'Other')], max_length=20),
        ),
    ]
