# Generated by Django 5.2.15 on 2026-07-25 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0053_store_meta_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('focus', 'Focus NFe'), ('sefaz', 'SEFAZ direto')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Processando'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('error', 'Erro')], default='pending', max_length=20)),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=44)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('qrcode_url', models.TextField(blank=True)),
                ('danfe_url', models.TextField(blank=True)),
                ('xml_url', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='stores.storeorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_documents', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='fiscal_fisc_store_i_0e0680_idx'), models.Index(fields=['order'], name='fiscal_fisc_order_i_0db9f9_idx')],
            },
        ),
    ]
