# Generated by Django 5.2.17 on 2026-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='modelo',
            field=models.CharField(choices=[('65', 'NFC-e'), ('55', 'NF-e')], default='65', max_length=2),
        ),
    ]
