# Generated by Django 4.2 on 2026-02-02 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0019_remove_storepaymentwebhookevent_store_pay_webhook_gateway_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('mercadopago', 'Mercado Pago'), ('custom', 'Custom')], max_length=20)),
                ('path', models.CharField(help_text='URL path segment', max_length=100, unique=True)),
                ('secret', models.CharField(blank=True, help_text='Secret for signature verification', max_length=255)),
                ('verify_token', models.CharField(blank=True, help_text='Verification token (for challenge-response)', max_length=255)),
                ('signature_header', models.CharField(blank=True, default='X-Hub-Signature-256', help_text='Header containing signature', max_length=100)),
                ('handler_class', models.CharField(help_text='Python path to handler class', max_length=255)),
                ('log_payloads', models.BooleanField(default=True)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'db_table': 'webhook_endpoints',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('mercadopago', 'Mercado Pago'), ('automation', 'Automation'), ('custom', 'Custom')], max_length=20)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('query_params', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(null=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('handler_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='stores.store')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('endpoint_url', models.URLField()),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Delivery Attempt',
                'verbose_name_plural': 'Webhook Delivery Attempts',
                'db_table': 'webhook_delivery_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'event_type'], name='webhooks_ev_provide_3c6f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'status'], name='webhooks_ev_provide_4c8e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id'], name='webhooks_ev_event_i_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['created_at'], name='webhooks_ev_created_a1b2c3_idx'),
        ),
    ]
