# Generated by Django 4.2.28 on 2026-02-20 02:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('webhooks', '0002_add_dlq_and_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('endpoint_url', models.URLField()),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Delivery Attempt',
                'verbose_name_plural': 'Webhook Delivery Attempts',
                'db_table': 'webhook_delivery_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('mercadopago', 'Mercado Pago'), ('custom', 'Custom')], max_length=20)),
                ('path', models.CharField(help_text='URL path segment', max_length=100, unique=True)),
                ('secret', models.CharField(blank=True, help_text='Secret for signature verification', max_length=255)),
                ('verify_token', models.CharField(blank=True, help_text='Verification token (for challenge-response)', max_length=255)),
                ('signature_header', models.CharField(blank=True, default='X-Hub-Signature-256', help_text='Header containing signature', max_length=100)),
                ('handler_class', models.CharField(help_text='Python path to handler class', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('log_payloads', models.BooleanField(default=True)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'db_table': 'webhook_endpoints',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('mercadopago', 'Mercado Pago'), ('automation', 'Automation'), ('custom', 'Custom')], max_length=20)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('query_params', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(null=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('handler_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='webhookdeadletter',
            new_name='webhook_dea_status_9a93ed_idx',
            old_name='webhook_dlq_status_reason_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeadletter',
            new_name='webhook_dea_provide_432564_idx',
            old_name='webhook_dlq_provider_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeadletter',
            new_name='webhook_dea_failure_8d5f3f_idx',
            old_name='webhook_dlq_signature_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeadletter',
            new_name='webhook_dea_event_i_391072_idx',
            old_name='webhook_dlq_event_id_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookoutbox',
            new_name='webhook_out_status_6b462c_idx',
            old_name='webhook_outbox_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookoutbox',
            new_name='webhook_out_status_84479d_idx',
            old_name='webhook_outbox_status_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookoutbox',
            new_name='webhook_out_idempot_3dd761_idx',
            old_name='webhook_outbox_idempotency_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookoutbox',
            new_name='webhook_out_store_i_e3c633_idx',
            old_name='webhook_outbox_store_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookoutbox',
            new_name='webhook_out_event_t_3ddc3f_idx',
            old_name='webhook_outbox_event_status_idx',
        ),
        migrations.AddField(
            model_name='webhookdeadletter',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='webhookoutbox',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='webhookdeadletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='webhookoutbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='webhookdeadletter',
            index=models.Index(fields=['created_at'], name='webhook_dea_created_6477b9_idx'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'event_type'], name='webhook_eve_provide_2e40e6_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'status'], name='webhook_eve_provide_a96dda_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id'], name='webhook_eve_event_i_bb7559_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['created_at'], name='webhook_eve_created_8fa52f_idx'),
        ),
    ]
