# Generated by Django 4.2.30 on 2026-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_webhookdeliveryattempt_webhookendpoint_webhookevent_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'created_at'], name='webhook_eve_provide_aa270e_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id__gt', '')), fields=('provider', 'event_id'), name='unique_webhook_event_per_provider'),
        ),
    ]
