# Generated by Django 5.2.17 on 2026-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_webhookevent_webhook_eve_provide_aa270e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='provider',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('mercadopago', 'Mercado Pago'), ('pagarme', 'Pagar.me'), ('toca-delivery', 'Toca Delivery'), ('custom', 'Custom')], max_length=20),
        ),
    ]
