# Generated by Django 5.2.14 on 2026-05-28 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_storeorder_created_by_staff_and_more'),
        ('users', '0002_unifieduser_django_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Casa', max_length=50, verbose_name='Rótulo')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant/store this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store')),
                ('unified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.unifieduser', verbose_name='Usuário')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço do Usuário',
                'verbose_name_plural': 'Endereços dos Usuários',
                'db_table': 'user_addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['unified_user', 'tenant'], name='user_addres_unified_dfde37_idx'), models.Index(fields=['unified_user', 'is_default'], name='user_addres_unified_8465da_idx')],
            },
        ),
    ]
