# Generated by Django 5.2.17 on 2026-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='complement',
            field=models.CharField(blank=True, help_text='"ao lado da GoFit", "portão azul", "apto 302".', max_length=255, verbose_name='Complemento'),
        ),
    ]
