# Generated by Django 4.2.27 on 2026-01-09 03:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('conversations', '0002_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurante'), ('ecommerce', 'E-commerce'), ('services', 'Serviços'), ('retail', 'Varejo'), ('healthcare', 'Saúde'), ('education', 'Educação'), ('other', 'Outro')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('menu_url', models.URLField(blank=True, help_text='URL do cardápio/catálogo')),
                ('order_url', models.URLField(blank=True, help_text='URL para fazer pedidos')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Horário de funcionamento por dia da semana')),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('welcome_message_enabled', models.BooleanField(default=True)),
                ('menu_auto_send', models.BooleanField(default=True, help_text='Enviar cardápio automaticamente na primeira mensagem')),
                ('abandoned_cart_notification', models.BooleanField(default=True)),
                ('abandoned_cart_delay_minutes', models.PositiveIntegerField(default=30, help_text='Minutos para esperar antes de notificar carrinho abandonado')),
                ('pix_notification_enabled', models.BooleanField(default=True)),
                ('payment_confirmation_enabled', models.BooleanField(default=True)),
                ('order_status_notification_enabled', models.BooleanField(default=True)),
                ('delivery_notification_enabled', models.BooleanField(default=True)),
                ('external_api_key', models.CharField(blank=True, help_text='API key para o site externo se conectar', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret para validar webhooks do site', max_length=255)),
                ('use_langflow', models.BooleanField(default=False, help_text='Usar Langflow para respostas avançadas')),
                ('langflow_flow_id', models.UUIDField(blank=True, help_text='ID do flow no Langflow', null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configurações personalizadas')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('session_id', models.CharField(db_index=True, help_text='ID da sessão no site externo', max_length=100, unique=True)),
                ('external_customer_id', models.CharField(blank=True, help_text='ID do cliente no site externo', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('checkout', 'Em Checkout'), ('payment_pending', 'Aguardando Pagamento'), ('payment_confirmed', 'Pagamento Confirmado'), ('order_placed', 'Pedido Realizado'), ('completed', 'Concluída'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('cart_data', models.JSONField(blank=True, default=dict, help_text='Dados do carrinho')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart_items_count', models.PositiveIntegerField(default=0)),
                ('cart_created_at', models.DateTimeField(blank=True, null=True)),
                ('cart_updated_at', models.DateTimeField(blank=True, null=True)),
                ('pix_code', models.TextField(blank=True)),
                ('pix_qr_code', models.TextField(blank=True)),
                ('pix_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('external_order_id', models.CharField(blank=True, help_text='ID do pedido no site externo', max_length=100)),
                ('notifications_sent', models.JSONField(blank=True, default=list, help_text='Lista de notificações enviadas')),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sessions', to='automation.companyprofile')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sessions', to='conversations.conversation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sessions', to='stores.storeorder')),
            ],
            options={
                'verbose_name': 'Customer Session',
                'verbose_name_plural': 'Customer Sessions',
                'db_table': 'customer_sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('welcome', 'Boas-vindas'), ('menu', 'Cardápio/Catálogo'), ('business_hours', 'Horário de Funcionamento'), ('out_of_hours', 'Fora do Horário'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('cart_reminder', 'Lembrete de Carrinho'), ('pix_generated', 'PIX Gerado'), ('pix_reminder', 'Lembrete de PIX'), ('pix_expired', 'PIX Expirado'), ('payment_confirmed', 'Pagamento Confirmado'), ('payment_failed', 'Pagamento Falhou'), ('order_confirmed', 'Pedido Confirmado'), ('order_preparing', 'Pedido em Preparo'), ('order_ready', 'Pedido Pronto'), ('order_shipped', 'Pedido Enviado'), ('order_out_for_delivery', 'Saiu para Entrega'), ('order_delivered', 'Pedido Entregue'), ('order_cancelled', 'Pedido Cancelado'), ('feedback_request', 'Solicitar Avaliação'), ('custom', 'Personalizado')], max_length=30)),
                ('name', models.CharField(help_text='Nome interno da mensagem', max_length=255)),
                ('message_text', models.TextField(help_text='Texto da mensagem. Use {variáveis} para personalização')),
                ('media_url', models.URLField(blank=True, help_text='URL de imagem/documento para enviar junto')),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vídeo')], max_length=20)),
                ('buttons', models.JSONField(blank=True, default=list, help_text="Botões interativos [{'id': 'btn1', 'title': 'Texto'}]")),
                ('is_active', models.BooleanField(default=True)),
                ('delay_seconds', models.PositiveIntegerField(default=0, help_text='Segundos para esperar antes de enviar')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Condições para enviar a mensagem')),
                ('priority', models.PositiveIntegerField(default=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_messages', to='automation.companyprofile')),
            ],
            options={
                'verbose_name': 'Auto Message',
                'verbose_name_plural': 'Auto Messages',
                'db_table': 'auto_messages',
                'ordering': ['company', 'event_type', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action_type', models.CharField(choices=[('message_received', 'Mensagem Recebida'), ('message_sent', 'Mensagem Enviada'), ('webhook_received', 'Webhook Recebido'), ('session_created', 'Sessão Criada'), ('session_updated', 'Sessão Atualizada'), ('notification_sent', 'Notificação Enviada'), ('error', 'Erro')], max_length=30)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='automation.companyprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.customersession')),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'db_table': 'automation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customersession',
            index=models.Index(fields=['company', 'phone_number', '-created_at'], name='customer_se_company_17e67d_idx'),
        ),
        migrations.AddIndex(
            model_name='customersession',
            index=models.Index(fields=['session_id'], name='customer_se_session_ea5409_idx'),
        ),
        migrations.AddIndex(
            model_name='customersession',
            index=models.Index(fields=['status', '-last_activity_at'], name='customer_se_status_8261cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automessage',
            unique_together={('company', 'event_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['company', '-created_at'], name='automation__company_e6b547_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['action_type', '-created_at'], name='automation__action__769885_idx'),
        ),
    ]
