# Generated by Django 4.2.27 on 2026-01-09 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('messages', 'Mensagens'), ('orders', 'Pedidos'), ('conversations', 'Conversas'), ('automation', 'Automação'), ('payments', 'Pagamentos'), ('full', 'Completo')], default='full', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='weekly', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(default=1, help_text='Day of week for weekly reports (1=Monday, 7=Sunday)')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day of month for monthly reports')),
                ('hour', models.PositiveSmallIntegerField(default=8, help_text='Hour to send report (0-23)')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send report to')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('disabled', 'Desativado')], default='active', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('include_charts', models.BooleanField(default=True)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], default='xlsx', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(blank=True, help_text='Filter by account (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='whatsapp.whatsappaccount')),
                ('company', models.ForeignKey(blank=True, help_text='Filter by company (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='automation.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='generating', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_format', models.CharField(default='xlsx', max_length=10)),
                ('records_count', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='automation.reportschedule')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('to_number', models.CharField(db_index=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('template', 'Template'), ('image', 'Imagem'), ('document', 'Documento'), ('interactive', 'Interativo')], default='text', max_length=20)),
                ('message_text', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('template_language', models.CharField(default='pt_BR', max_length=10)),
                ('template_components', models.JSONField(blank=True, default=list)),
                ('media_url', models.URLField(blank=True)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_scheduled_messages', to='whatsapp.whatsappaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_scheduled_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Message',
                'verbose_name_plural': 'Scheduled Messages',
                'db_table': 'automation_scheduled_messages',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['account', 'status', 'scheduled_at'], name='automation__account_7d45de_idx'), models.Index(fields=['status', 'scheduled_at'], name='automation__status_8a3224_idx')],
            },
        ),
    ]
