# Generated by Django 4.2.27 on 2026-01-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_customer_session_store_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduledmessage',
            new_name='scheduled_m_account_8f1cce_idx',
            old_name='automation__account_7d45de_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledmessage',
            new_name='scheduled_m_status_c4bde9_idx',
            old_name='automation__status_8a3224_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledmessage',
            new_name='scheduled_m_source_7700e8_idx',
            old_name='scheduled_m_source_a1b2c3_idx',
        ),
    ]
