# Generated by Django 4.2.27 on 2026-01-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_companyprofile_store_and_renames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='_business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('ecommerce', 'E-commerce'), ('services', 'Serviços'), ('retail', 'Varejo'), ('healthcare', 'Saúde'), ('education', 'Educação'), ('other', 'Outro')], db_column='business_type', default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='_company_name',
            field=models.CharField(db_column='company_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='_description',
            field=models.TextField(blank=True, db_column='description'),
        ),
    ]
