# Generated by Django 4.2 on 2026-02-02 04:30

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge migration to resolve conflict between:
    - 0006_add_store_to_companyprofile
    - 0006_companyprofile_store_and_renames
    - 0007_alter_companyprofile__business_type_and_more
    """

    dependencies = [
        ('automation', '0006_companyprofile_store_and_renames'),
        ('automation', '0007_alter_companyprofile__business_type_and_more'),
    ]

    operations = [
    ]
