# Generated by Django 4.2.27 on 2026-03-13 02:27

import json

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class CreateModelIfMissing(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table in schema_editor.connection.introspection.table_names():
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddFieldIfMissing(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
            }
        field = model._meta.get_field(self.name)
        if field.column in columns:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfMissing(migrations.AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)
        if self.index.name in constraints:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RenameIndexIfExists(migrations.RenameIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)
        if self.new_name in constraints or self.old_name not in constraints:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AlterModelTableIfNeeded(migrations.AlterModelTable):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        old_model = from_state.apps.get_model(app_label, self.name)
        new_model = to_state.apps.get_model(app_label, self.name)
        existing_tables = set(schema_editor.connection.introspection.table_names())
        if new_model._meta.db_table in existing_tables:
            return
        if old_model._meta.db_table not in existing_tables:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def normalize_company_profile_business_hours(apps, schema_editor):
    table_name = 'company_profiles'
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'SELECT id, business_hours FROM {table_name}')
        rows = cursor.fetchall()
        for profile_id, raw_value in rows:
            if isinstance(raw_value, dict):
                normalized = raw_value
            else:
                text = (raw_value or '').strip()
                if not text:
                    normalized = {}
                else:
                    try:
                        loaded = json.loads(text)
                        normalized = loaded if isinstance(loaded, dict) else {}
                    except Exception:
                        normalized = {}
            cursor.execute(
                f'UPDATE {table_name} SET business_hours = %s WHERE id = %s',
                [json.dumps(normalized), profile_id],
            )

        if schema_editor.connection.vendor == 'postgresql':
            cursor.execute(
                f"""
                ALTER TABLE {table_name}
                ALTER COLUMN business_hours TYPE jsonb
                USING business_hours::jsonb
                """
            )


def backfill_auto_message_names(apps, schema_editor):
    AutoMessage = apps.get_model('automation', 'AutoMessage')
    grouped = {}
    for message in AutoMessage.objects.all().order_by('company_id', 'event_type', 'created_at', 'id'):
        key = (message.company_id, message.event_type)
        grouped[key] = grouped.get(key, 0) + 1
        suffix = grouped[key]
        base_name = message.event_type or 'legacy'
        message.name = base_name if suffix == 1 else f'{base_name}_{suffix}'
        message.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
        ('whatsapp', '0003_sync_message_context_and_analytics'),
        ('agents', '0006_agent_max_context_messages_and_more'),
        ('conversations', '0004_merge'),
        ('automation', '0007_add_flow_builder_models'),
    ]

    operations = [
        CreateModelIfMissing(
            name='AgentFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('flow_json', models.JSONField(default=dict, help_text='Estrutura do React Flow: {nodes: [], edges: []}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Se verdadeiro, ï¿½ o fluxo padrï¿½o da loja')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('total_executions', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Fluxo de Atendimento',
                'verbose_name_plural': 'Fluxos de Atendimento',
                'db_table': 'agent_flows',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        CreateModelIfMissing(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action_type', models.CharField(choices=[('message_received', 'Mensagem Recebida'), ('message_sent', 'Mensagem Enviada'), ('webhook_received', 'Webhook Recebido'), ('session_created', 'Sessï¿½o Criada'), ('session_updated', 'Sessï¿½o Atualizada'), ('notification_sent', 'Notificaï¿½ï¿½o Enviada'), ('error', 'Erro')], max_length=30)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'db_table': 'automation_logs',
                'ordering': ['-created_at'],
            },
        ),
        CreateModelIfMissing(
            name='CustomerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('session_id', models.CharField(db_index=True, help_text='ID da sessï¿½o no site externo', max_length=100, unique=True)),
                ('external_customer_id', models.CharField(blank=True, help_text='ID do cliente no site externo', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('checkout', 'Em Checkout'), ('payment_pending', 'Aguardando Pagamento'), ('payment_confirmed', 'Pagamento Confirmado'), ('order_placed', 'Pedido Realizado'), ('completed', 'Concluï¿½da'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('cart_data', models.JSONField(blank=True, default=dict, help_text='Dados do carrinho')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart_items_count', models.PositiveIntegerField(default=0)),
                ('cart_created_at', models.DateTimeField(blank=True, null=True)),
                ('cart_updated_at', models.DateTimeField(blank=True, null=True)),
                ('pix_code', models.TextField(blank=True)),
                ('pix_qr_code', models.TextField(blank=True)),
                ('pix_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('external_order_id', models.CharField(blank=True, help_text='ID do pedido no site externo', max_length=100)),
                ('notifications_sent', models.JSONField(blank=True, default=list, help_text='Lista de notificaï¿½ï¿½es enviadas')),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Session',
                'verbose_name_plural': 'Customer Sessions',
                'db_table': 'customer_sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        CreateModelIfMissing(
            name='FlowExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('node_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(max_length=50)),
                ('input_message', models.TextField(blank=True)),
                ('output_message', models.TextField(blank=True)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Execuï¿½ï¿½o',
                'verbose_name_plural': 'Logs de Execuï¿½ï¿½o',
                'db_table': 'flow_execution_logs',
                'ordering': ['-created_at'],
            },
        ),
        CreateModelIfMissing(
            name='FlowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('current_node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.JSONField(default=dict, help_text='Variï¿½veis coletadas durante o fluxo')),
                ('node_history', models.JSONField(default=list, help_text='Lista de nï¿½s visitados')),
                ('is_waiting_input', models.BooleanField(default=False)),
                ('input_type_expected', models.CharField(blank=True, max_length=50)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sessï¿½o de Fluxo',
                'verbose_name_plural': 'Sessï¿½es de Fluxo',
                'db_table': 'flow_sessions',
            },
        ),
        CreateModelIfMissing(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('completed', 'Concluï¿½do'), ('failed', 'Falhou')], default='generating', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_format', models.CharField(default='xlsx', max_length=10)),
                ('records_count', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
        CreateModelIfMissing(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('messages', 'Mensagens'), ('orders', 'Pedidos'), ('conversations', 'Conversas'), ('automation', 'Automaï¿½ï¿½o'), ('payments', 'Pagamentos'), ('full', 'Completo')], default='full', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Diï¿½rio'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='weekly', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(default=1, help_text='Day of week for weekly reports (1=Monday, 7=Sunday)')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day of month for monthly reports')),
                ('hour', models.PositiveSmallIntegerField(default=8, help_text='Hour to send report (0-23)')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send report to')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('disabled', 'Desativado')], default='active', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('include_charts', models.BooleanField(default=True)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], default='xlsx', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedules',
                'ordering': ['name'],
            },
        ),
        CreateModelIfMissing(
            name='ScheduledMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('to_number', models.CharField(db_index=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('template', 'Template'), ('image', 'Imagem'), ('document', 'Documento'), ('interactive', 'Interativo')], default='text', max_length=20)),
                ('message_text', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('template_language', models.CharField(default='pt_BR', max_length=10)),
                ('template_components', models.JSONField(blank=True, default=list)),
                ('media_url', models.URLField(blank=True)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Additional content data')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE format', max_length=255)),
                ('next_occurrence', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='manual', help_text='Source: manual, campaign, automation, api', max_length=20)),
                ('campaign_id', models.UUIDField(blank=True, help_text='Related campaign if from campaign', null=True)),
            ],
            options={
                'verbose_name': 'Scheduled Message',
                'verbose_name_plural': 'Scheduled Messages',
                'db_table': 'scheduled_messages',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='automessage',
            options={'ordering': ['company', 'event_type', 'priority'], 'verbose_name': 'Auto Message', 'verbose_name_plural': 'Auto Messages'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        AlterModelTableIfNeeded(
            name='automessage',
            table='auto_messages',
        ),
        AlterModelTableIfNeeded(
            name='companyprofile',
            table='company_profiles',
        ),
        RenameIndexIfExists(
            model_name='intentlog',
            new_name='intent_logs_intent__56f1b3_idx',
            old_name='intent_logs_inten_029f4c_idx',
        ),
        RenameIndexIfExists(
            model_name='intentlog',
            new_name='intent_logs_method_83e4ce_idx',
            old_name='intent_logs_metho_5e2e61_idx',
        ),
        RenameIndexIfExists(
            model_name='intentlog',
            new_name='intent_logs_phone_n_4bd5d4_idx',
            old_name='intent_logs_phone_8593b5_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='companyprofile',
                    name='address',
                ),
                migrations.RemoveField(
                    model_name='companyprofile',
                    name='business_hours',
                ),
                migrations.RemoveField(
                    model_name='companyprofile',
                    name='company_name',
                ),
                migrations.RemoveField(
                    model_name='companyprofile',
                    name='whatsapp_number',
                ),
                migrations.AddField(
                    model_name='companyprofile',
                    name='_business_hours',
                    field=models.JSONField(
                        blank=True,
                        db_column='business_hours',
                        default=dict,
                        help_text='DEPRECATED: Use store.operating_hours instead',
                    ),
                ),
                migrations.AddField(
                    model_name='companyprofile',
                    name='_company_name',
                    field=models.CharField(blank=True, db_column='company_name', max_length=255),
                ),
            ],
        ),
        migrations.RunPython(normalize_company_profile_business_hours, migrations.RunPython.noop),
        AddFieldIfMissing(
            model_name='automessage',
            name='buttons',
            field=models.JSONField(blank=True, default=list, help_text="Botï¿½es interativos [{'id': 'btn1', 'title': 'Texto'}]"),
        ),
        AddFieldIfMissing(
            model_name='automessage',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Condiï¿½ï¿½es para enviar a mensagem'),
        ),
        AddFieldIfMissing(
            model_name='automessage',
            name='delay_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Segundos para esperar antes de enviar'),
        ),
        AddFieldIfMissing(
            model_name='automessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vï¿½deo')], max_length=20),
        ),
        AddFieldIfMissing(
            model_name='automessage',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL de imagem/documento para enviar junto'),
        ),
        AddFieldIfMissing(
            model_name='automessage',
            name='name',
            field=models.CharField(default='', help_text='Nome interno da mensagem', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_auto_message_names, migrations.RunPython.noop),
        AddFieldIfMissing(
            model_name='automessage',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='_business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('ecommerce', 'E-commerce'), ('services', 'Serviï¿½os'), ('retail', 'Varejo'), ('healthcare', 'Saï¿½de'), ('education', 'Educaï¿½ï¿½o'), ('other', 'Outro')], db_column='business_type', default='other', max_length=20),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='_description',
            field=models.TextField(blank=True, db_column='description'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='abandoned_cart_delay_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutos para esperar antes de notificar carrinho abandonado'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='abandoned_cart_notification',
            field=models.BooleanField(default=True),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='whatsapp.whatsappaccount'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='auto_reply_enabled',
            field=models.BooleanField(default=True),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='default_agent',
            field=models.ForeignKey(blank=True, help_text='Agente IA padrï¿½o para respostas automï¿½ticas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='agents.agent'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='delivery_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='external_api_key',
            field=models.CharField(blank=True, help_text='API key para o site externo se conectar', max_length=255),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='menu_auto_send',
            field=models.BooleanField(default=True, help_text='Enviar cardï¿½pio automaticamente na primeira mensagem'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='menu_url',
            field=models.URLField(blank=True, help_text='URL do cardï¿½pio/catï¿½logo'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='order_status_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='order_url',
            field=models.URLField(blank=True, help_text='URL para fazer pedidos'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='payment_confirmation_enabled',
            field=models.BooleanField(default=True),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='pix_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Configuraï¿½ï¿½es personalizadas'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_profile', to='stores.store'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='use_ai_agent',
            field=models.BooleanField(default=False, help_text='Usar Agente IA (Langchain) para respostas avanï¿½adas'),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret para validar webhooks do site', max_length=255),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        AddFieldIfMissing(
            model_name='companyprofile',
            name='welcome_message_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_messages', to='automation.companyprofile'),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='message_text',
            field=models.TextField(help_text='Texto da mensagem. Use {variï¿½veis} para personalizaï¿½ï¿½o'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='intentlog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name='automessage',
            unique_together={('company', 'event_type', 'name')},
        ),
        AddFieldIfMissing(
            model_name='scheduledmessage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='whatsapp.whatsappaccount'),
        ),
        AddFieldIfMissing(
            model_name='scheduledmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfMissing(
            model_name='reportschedule',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Filter by account (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='whatsapp.whatsappaccount'),
        ),
        AddFieldIfMissing(
            model_name='reportschedule',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Filter by company (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='automation.companyprofile'),
        ),
        AddFieldIfMissing(
            model_name='reportschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfMissing(
            model_name='generatedreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfMissing(
            model_name='generatedreport',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='automation.reportschedule'),
        ),
        AddFieldIfMissing(
            model_name='flowsession',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_session', to='conversations.conversation'),
        ),
        AddFieldIfMissing(
            model_name='flowsession',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='automation.agentflow'),
        ),
        AddFieldIfMissing(
            model_name='flowexecutionlog',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='automation.agentflow'),
        ),
        AddFieldIfMissing(
            model_name='flowexecutionlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='automation.flowsession'),
        ),
        AddFieldIfMissing(
            model_name='customersession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sessions', to='automation.companyprofile'),
        ),
        AddFieldIfMissing(
            model_name='customersession',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sessions', to='conversations.conversation'),
        ),
        AddFieldIfMissing(
            model_name='customersession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sessions', to='stores.storeorder'),
        ),
        AddFieldIfMissing(
            model_name='automationlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='automation.companyprofile'),
        ),
        AddFieldIfMissing(
            model_name='automationlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.customersession'),
        ),
        AddFieldIfMissing(
            model_name='agentflow',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='stores.store'),
        ),
        AddIndexIfMissing(
            model_name='scheduledmessage',
            index=models.Index(fields=['account', 'status', 'scheduled_at'], name='scheduled_m_account_8f1cce_idx'),
        ),
        AddIndexIfMissing(
            model_name='scheduledmessage',
            index=models.Index(fields=['status', 'scheduled_at'], name='scheduled_m_status_c4bde9_idx'),
        ),
        AddIndexIfMissing(
            model_name='scheduledmessage',
            index=models.Index(fields=['source', 'status'], name='scheduled_m_source_7700e8_idx'),
        ),
        AddIndexIfMissing(
            model_name='customersession',
            index=models.Index(fields=['company', 'phone_number', '-created_at'], name='customer_se_company_17e67d_idx'),
        ),
        AddIndexIfMissing(
            model_name='customersession',
            index=models.Index(fields=['session_id'], name='customer_se_session_ea5409_idx'),
        ),
        AddIndexIfMissing(
            model_name='customersession',
            index=models.Index(fields=['status', '-last_activity_at'], name='customer_se_status_8261cd_idx'),
        ),
        AddIndexIfMissing(
            model_name='automationlog',
            index=models.Index(fields=['company', '-created_at'], name='automation__company_e6b547_idx'),
        ),
        AddIndexIfMissing(
            model_name='automationlog',
            index=models.Index(fields=['action_type', '-created_at'], name='automation__action__769885_idx'),
        ),
    ]
