# Generated by Django 4.2.27 on 2026-03-13 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_max_context_messages_and_more'),
        ('automation', '0008_agentflow_automationlog_customersession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowexecutionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de Execução', 'verbose_name_plural': 'Logs de Execução'},
        ),
        migrations.AlterModelOptions(
            name='flowsession',
            options={'verbose_name': 'Sessão de Fluxo', 'verbose_name_plural': 'Sessões de Fluxo'},
        ),
        migrations.AlterField(
            model_name='agentflow',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, é o fluxo padrão da loja'),
        ),
        migrations.AlterField(
            model_name='automationlog',
            name='action_type',
            field=models.CharField(choices=[('message_received', 'Mensagem Recebida'), ('message_sent', 'Mensagem Enviada'), ('webhook_received', 'Webhook Recebido'), ('session_created', 'Sessão Criada'), ('session_updated', 'Sessão Atualizada'), ('notification_sent', 'Notificação Enviada'), ('error', 'Erro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='buttons',
            field=models.JSONField(blank=True, default=list, help_text="Botões interativos [{'id': 'btn1', 'title': 'Texto'}]"),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Condições para enviar a mensagem'),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vídeo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='message_text',
            field=models.TextField(help_text='Texto da mensagem. Use {variáveis} para personalização'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='_business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('ecommerce', 'E-commerce'), ('services', 'Serviços'), ('retail', 'Varejo'), ('healthcare', 'Saúde'), ('education', 'Educação'), ('other', 'Outro')], db_column='business_type', default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='default_agent',
            field=models.ForeignKey(blank=True, help_text='Agente IA padrão para respostas automáticas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='menu_auto_send',
            field=models.BooleanField(default=True, help_text='Enviar cardápio automaticamente na primeira mensagem'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='menu_url',
            field=models.URLField(blank=True, help_text='URL do cardápio/catálogo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações personalizadas'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='use_ai_agent',
            field=models.BooleanField(default=False, help_text='Usar Agente IA (Langchain) para respostas avançadas'),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='notifications_sent',
            field=models.JSONField(blank=True, default=list, help_text='Lista de notificações enviadas'),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='session_id',
            field=models.CharField(db_index=True, help_text='ID da sessão no site externo', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('checkout', 'Em Checkout'), ('payment_pending', 'Aguardando Pagamento'), ('payment_confirmed', 'Pagamento Confirmado'), ('order_placed', 'Pedido Realizado'), ('completed', 'Concluída'), ('expired', 'Expirada')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='context',
            field=models.JSONField(default=dict, help_text='Variáveis coletadas durante o fluxo'),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='node_history',
            field=models.JSONField(default=list, help_text='Lista de nós visitados'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('generating', 'Gerando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='generating', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('messages', 'Mensagens'), ('orders', 'Pedidos'), ('conversations', 'Conversas'), ('automation', 'Automação'), ('payments', 'Pagamentos'), ('full', 'Completo')], default='full', max_length=20),
        ),
    ]
