# Generated by Django 5.2 on 2026-03-03 15:11
# Manual merge migration to resolve conflict between 0002 and 0009

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0008_consolidate_store"),
        ("automation", "0009_agentflow_automationlog_customersession_and_more"),
    ]

    operations = []
