# Generated by Django 4.2.27 on 2026-03-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_max_context_messages_and_more'),
        ('automation', '0011_canonicalize_store_profile_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowexecutionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de ExecuÃ§Ã£o', 'verbose_name_plural': 'Logs de ExecuÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='flowsession',
            options={'verbose_name': 'SessÃ£o de Fluxo', 'verbose_name_plural': 'SessÃµes de Fluxo'},
        ),
        migrations.AlterField(
            model_name='agentflow',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, Ã© o fluxo padrÃ£o da loja'),
        ),
        migrations.AlterField(
            model_name='automationlog',
            name='action_type',
            field=models.CharField(choices=[('message_received', 'Mensagem Recebida'), ('message_sent', 'Mensagem Enviada'), ('webhook_received', 'Webhook Recebido'), ('session_created', 'SessÃ£o Criada'), ('session_updated', 'SessÃ£o Atualizada'), ('notification_sent', 'NotificaÃ§Ã£o Enviada'), ('error', 'Erro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='buttons',
            field=models.JSONField(blank=True, default=list, help_text="BotÃµes interativos [{'id': 'btn1', 'title': 'Texto'}]"),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='CondiÃ§Ãµes para enviar a mensagem'),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='event_type',
            field=models.CharField(choices=[('welcome', 'Boas-vindas'), ('menu', 'CardÃ¡pio/CatÃ¡logo'), ('business_hours', 'HorÃ¡rio de Funcionamento'), ('out_of_hours', 'Fora do HorÃ¡rio'), ('faq', 'Perguntas Frequentes'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('cart_reminder', 'Lembrete de Carrinho'), ('cart_reminder_30', 'Lembrete Carrinho (30min)'), ('cart_reminder_2h', 'Lembrete Carrinho (2h)'), ('cart_reminder_24h', 'Lembrete Carrinho (24h)'), ('pix_generated', 'PIX Gerado'), ('pix_reminder', 'Lembrete de PIX'), ('pix_expired', 'PIX Expirado'), ('payment_confirmed', 'Pagamento Confirmado'), ('payment_failed', 'Pagamento Falhou'), ('payment_reminder_1', 'Lembrete Pagamento (30min)'), ('payment_reminder_2', 'Lembrete Pagamento (2h)'), ('order_received', 'Pedido Recebido'), ('order_confirmed', 'Pedido Confirmado'), ('order_preparing', 'Pedido em Preparo'), ('order_ready', 'Pedido Pronto'), ('order_shipped', 'Pedido Enviado'), ('order_out_for_delivery', 'Saiu para Entrega'), ('order_delivered', 'Pedido Entregue'), ('order_cancelled', 'Pedido Cancelado'), ('feedback_request', 'Solicitar AvaliaÃ§Ã£o'), ('feedback_received', 'AvaliaÃ§Ã£o Recebida'), ('human_handoff', 'Transferido para Humano'), ('human_assigned', 'Atendente AtribuÃ\xaddo'), ('custom', 'Personalizado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'VÃ\xaddeo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='message_text',
            field=models.TextField(help_text='Texto da mensagem. Use {variÃ¡veis} para personalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='_business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('ecommerce', 'E-commerce'), ('services', 'Servicos'), ('retail', 'Varejo'), ('healthcare', 'Saude'), ('education', 'Educacao'), ('other', 'Outro')], db_column='business_type', default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='default_agent',
            field=models.ForeignKey(blank=True, help_text='Agente IA padrao para respostas automaticas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='menu_auto_send',
            field=models.BooleanField(default=True, help_text='Enviar cardapio automaticamente na primeira mensagem'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='menu_url',
            field=models.URLField(blank=True, help_text='URL do cardapio/catalogo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Configuracoes personalizadas'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='use_ai_agent',
            field=models.BooleanField(default=False, help_text='Usar Agente IA (Langchain) para respostas avancadas'),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='notifications_sent',
            field=models.JSONField(blank=True, default=list, help_text='Lista de notificaÃ§Ãµes enviadas'),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='session_id',
            field=models.CharField(db_index=True, help_text='ID da sessÃ£o no site externo', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('checkout', 'Em Checkout'), ('payment_pending', 'Aguardando Pagamento'), ('payment_confirmed', 'Pagamento Confirmado'), ('order_placed', 'Pedido Realizado'), ('completed', 'ConcluÃ\xadda'), ('expired', 'Expirada')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='context',
            field=models.JSONField(default=dict, help_text='VariÃ¡veis coletadas durante o fluxo'),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='node_history',
            field=models.JSONField(default=list, help_text='Lista de nÃ³s visitados'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('generating', 'Gerando'), ('completed', 'ConcluÃ\xaddo'), ('failed', 'Falhou')], default='generating', max_length=20),
        ),
        migrations.AlterField(
            model_name='intentlog',
            name='response_type',
            field=models.CharField(choices=[('text', 'Texto'), ('buttons', 'BotÃµes'), ('list', 'Lista'), ('interactive', 'Interativo')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'DiÃ¡rio'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('messages', 'Mensagens'), ('orders', 'Pedidos'), ('conversations', 'Conversas'), ('automation', 'AutomaÃ§Ã£o'), ('payments', 'Pagamentos'), ('full', 'Completo')], default='full', max_length=20),
        ),
    ]
