# Generated by Django 4.2.27 on 2026-03-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_alter_flowexecutionlog_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.CheckConstraint(check=models.Q(('store__isnull', False), ('account__isnull', False), _connector='OR'), name='company_profile_requires_store_or_account'),
        ),
    ]
