# Generated by Django 4.2.30 on 2026-05-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unifieduser_django_user'),
        ('automation', '0014_fix_pastita_hardcoded_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersession',
            name='unified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sessions', to='users.unifieduser'),
        ),
    ]
