# Generated by Django 5.2.14 on 2026-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_customersession_unified_user_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowexecutionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de Execução', 'verbose_name_plural': 'Logs de Execução'},
        ),
        migrations.AlterModelOptions(
            name='flowsession',
            options={'verbose_name': 'Sessão de Fluxo', 'verbose_name_plural': 'Sessões de Fluxo'},
        ),
        migrations.AlterField(
            model_name='agentflow',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, é o fluxo padrão da loja'),
        ),
        migrations.AlterField(
            model_name='automationlog',
            name='action_type',
            field=models.CharField(choices=[('message_received', 'Mensagem Recebida'), ('message_sent', 'Mensagem Enviada'), ('webhook_received', 'Webhook Recebido'), ('session_created', 'Sessão Criada'), ('session_updated', 'Sessão Atualizada'), ('notification_sent', 'Notificação Enviada'), ('error', 'Erro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='buttons',
            field=models.JSONField(blank=True, default=list, help_text="Botões interativos [{'id': 'btn1', 'title': 'Texto'}]"),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Condições para enviar a mensagem'),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='event_type',
            field=models.CharField(choices=[('welcome', 'Boas-vindas'), ('menu', 'Cardápio/Catálogo'), ('business_hours', 'Horário de Funcionamento'), ('out_of_hours', 'Fora do Horário'), ('faq', 'Perguntas Frequentes'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('cart_reminder', 'Lembrete de Carrinho'), ('cart_reminder_30', 'Lembrete Carrinho (30min)'), ('cart_reminder_2h', 'Lembrete Carrinho (2h)'), ('cart_reminder_24h', 'Lembrete Carrinho (24h)'), ('pix_generated', 'PIX Gerado'), ('pix_reminder', 'Lembrete de PIX'), ('pix_expired', 'PIX Expirado'), ('payment_confirmed', 'Pagamento Confirmado'), ('payment_failed', 'Pagamento Falhou'), ('payment_reminder_1', 'Lembrete Pagamento (30min)'), ('payment_reminder_2', 'Lembrete Pagamento (2h)'), ('order_received', 'Pedido Recebido'), ('order_confirmed', 'Pedido Confirmado'), ('order_preparing', 'Pedido em Preparo'), ('order_ready', 'Pedido Pronto'), ('order_shipped', 'Pedido Enviado'), ('order_out_for_delivery', 'Saiu para Entrega'), ('order_delivered', 'Pedido Entregue'), ('order_cancelled', 'Pedido Cancelado'), ('feedback_request', 'Solicitar Avaliação'), ('feedback_received', 'Avaliação Recebida'), ('human_handoff', 'Transferido para Humano'), ('human_assigned', 'Atendente Atribuído'), ('custom', 'Personalizado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vídeo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automessage',
            name='message_text',
            field=models.TextField(help_text='Texto da mensagem. Use {variáveis} para personalização'),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='notifications_sent',
            field=models.JSONField(blank=True, default=list, help_text='Lista de notificações enviadas'),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='session_id',
            field=models.CharField(db_index=True, help_text='ID da sessão no site externo', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customersession',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('cart_created', 'Carrinho Criado'), ('cart_abandoned', 'Carrinho Abandonado'), ('checkout', 'Em Checkout'), ('payment_pending', 'Aguardando Pagamento'), ('payment_confirmed', 'Pagamento Confirmado'), ('order_placed', 'Pedido Realizado'), ('completed', 'Concluída'), ('expired', 'Expirada')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='context',
            field=models.JSONField(default=dict, help_text='Variáveis coletadas durante o fluxo'),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='node_history',
            field=models.JSONField(default=list, help_text='Lista de nós visitados'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('generating', 'Gerando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='generating', max_length=20),
        ),
        migrations.AlterField(
            model_name='intentlog',
            name='response_type',
            field=models.CharField(choices=[('text', 'Texto'), ('buttons', 'Botões'), ('list', 'Lista'), ('interactive', 'Interativo')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('messages', 'Mensagens'), ('orders', 'Pedidos'), ('conversations', 'Conversas'), ('automation', 'Automação'), ('payments', 'Pagamentos'), ('full', 'Completo')], default='full', max_length=20),
        ),
    ]
