# Generated by Django 5.2.15 on 2026-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_alter_fields_meta_2026_05'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersession',
            name='delivery_address',
            field=models.TextField(blank=True, default='', help_text='Endereço de entrega'),
        ),
        migrations.AddField(
            model_name='customersession',
            name='delivery_method',
            field=models.CharField(default='delivery', help_text="Método de entrega: 'delivery' ou 'pickup'", max_length=20),
        ),
        migrations.AddField(
            model_name='customersession',
            name='payment_method',
            field=models.CharField(default='pix', help_text="Método de pagamento: 'pix', 'card', 'cash'", max_length=20),
        ),
    ]
