# Generated by Django 4.2.28 on 2026-02-09 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_add_conversions_api'),
        ('stores', '0001_add_conversions_api'),
        ('conversations', '0003_add_handover_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='stores.store'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='stores.store'),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.emailcampaign'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='stores.store'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailautomationlog',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.emailautomation'),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_automations', to='stores.store'),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='conversioneventbatch',
            name='events',
            field=models.ManyToManyField(related_name='batches', to='marketing.conversionevent', verbose_name='Eventos'),
        ),
        migrations.AddField(
            model_name='conversionevent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_events', to='conversations.conversation', verbose_name='Conversação'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['store', 'status'], name='marketing_s_store_i_75c7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['email'], name='marketing_s_email_7ce228_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('store', 'email')},
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['store', 'template_type'], name='marketing_e_store_i_028923_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['campaign', 'status'], name='marketing_e_campaig_e4e899_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['email'], name='marketing_e_email_a3c536_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailrecipient',
            unique_together={('campaign', 'email')},
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['store', 'status'], name='marketing_e_store_i_d5b86f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['scheduled_at'], name='marketing_e_schedul_50e7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailautomationlog',
            index=models.Index(fields=['automation', 'status'], name='marketing_e_automat_fd39aa_idx'),
        ),
        migrations.AddIndex(
            model_name='emailautomationlog',
            index=models.Index(fields=['recipient_email'], name='marketing_e_recipie_b4f751_idx'),
        ),
        migrations.AddIndex(
            model_name='emailautomation',
            index=models.Index(fields=['store', 'trigger_type', 'is_active'], name='marketing_e_store_i_d2d4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['event_name', 'status'], name='marketing_c_event_n_e1f534_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['source', 'status'], name='marketing_c_source_3ee819_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['event_time'], name='marketing_c_event_t_52eb18_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['created_at'], name='marketing_c_created_3a078e_idx'),
        ),
    ]
