# Generated by Django 4.2.30 on 2026-05-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class AddFieldIfMissing(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
            }
        field = model._meta.get_field(self.name)
        if field.column in columns:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unifieduser_django_user'),
        ('marketing', '0002_emailtemplates'),
    ]

    operations = [
        AddFieldIfMissing(
            model_name='subscriber',
            name='unified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_subscriptions', to='users.unifieduser', verbose_name='Identidade Universal'),
        ),
    ]
