# Generated by Django 4.2.27 on 2026-01-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_emailautomation_emailautomationlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailautomation',
            new_name='marketing_e_store_i_d2d4c9_idx',
            old_name='marketing_e_store_i_idx',
        ),
        migrations.RenameIndex(
            model_name='emailautomationlog',
            new_name='marketing_e_automat_fd39aa_idx',
            old_name='marketing_e_automat_idx',
        ),
        migrations.RenameIndex(
            model_name='emailautomationlog',
            new_name='marketing_e_recipie_b4f751_idx',
            old_name='marketing_e_recipie_idx',
        ),
    ]
