# Generated by Django 4.2.30 on 2026-05-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unifieduser_django_user'),
        ('marketing', '0002_emailtemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_subscriptions', to='users.unifieduser', verbose_name='Identidade Universal'),
        ),
    ]
