# Generated by Django 4.2.27 on 2026-01-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_rename_marketing_e_store_i_idx_marketing_e_store_i_d2d4c9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='audience_type',
            field=models.CharField(choices=[('all', 'Todos (subscribers + clientes)'), ('customers', 'Apenas clientes (que fizeram pedidos)'), ('subscribers', 'Apenas subscribers'), ('segment', 'Segmento'), ('custom', 'Lista personalizada')], default='all', max_length=20),
        ),
    ]
