# Generated by Django 4.2.27 on 2026-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_emailcampaign_audience_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailautomation',
            name='trigger_type',
            field=models.CharField(choices=[('new_user', 'Novo Usuário'), ('welcome', 'Boas-vindas'), ('order_received', 'Pedido Recebido'), ('order_confirmed', 'Pedido Confirmado'), ('order_preparing', 'Pedido em Preparo'), ('order_shipped', 'Pedido Enviado'), ('order_delivered', 'Pedido Entregue'), ('order_cancelled', 'Pedido Cancelado'), ('payment_pending', 'Pagamento Pendente'), ('payment_confirmed', 'Pagamento Confirmado'), ('payment_failed', 'Pagamento Falhou'), ('cart_abandoned', 'Carrinho Abandonado'), ('coupon_sent', 'Cupom Enviado'), ('birthday', 'Aniversário'), ('review_request', 'Solicitar Avaliação')], max_length=30),
        ),
    ]
