# Generated by Django 6.0.1 on 2026-01-09 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangflowFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('flow_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('endpoint_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], default='inactive', max_length=20)),
                ('input_type', models.CharField(default='chat', max_length=50)),
                ('output_type', models.CharField(default='chat', max_length=50)),
                ('tweaks', models.JSONField(blank=True, default=dict)),
                ('default_context', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('accounts', models.ManyToManyField(blank=True, related_name='langflow_flows', to='whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Langflow Flow',
                'verbose_name_plural': 'Langflow Flows',
                'db_table': 'langflow_flows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LangflowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('history', models.JSONField(blank=True, default=list)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langflow_sessions', to='conversations.conversation')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='langflow.langflowflow')),
            ],
            options={
                'verbose_name': 'Langflow Session',
                'verbose_name_plural': 'Langflow Sessions',
                'db_table': 'langflow_sessions',
                'ordering': ['-last_interaction_at'],
            },
        ),
        migrations.CreateModel(
            name='LangflowLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('input_message', models.TextField()),
                ('output_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='langflow.langflowflow')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='langflow.langflowsession')),
            ],
            options={
                'verbose_name': 'Langflow Log',
                'verbose_name_plural': 'Langflow Logs',
                'db_table': 'langflow_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flow', 'status', '-created_at'], name='langflow_lo_flow_id_0c2d9b_idx')],
            },
        ),
    ]
