# Generated by Django 4.2.28 on 2026-02-08 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('provider', models.CharField(choices=[('kimi', 'Kimi (Moonshot)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (Local)')], default='kimi', max_length=20, verbose_name='Provedor')),
                ('model_name', models.CharField(default='kimi-coder', max_length=100, verbose_name='Modelo')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('base_url', models.URLField(blank=True, default='https://api.moonshot.cn/v1', verbose_name='Base URL')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('max_tokens', models.PositiveIntegerField(default=1000, verbose_name='Max Tokens')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='Timeout (segundos)')),
                ('system_prompt', models.TextField(default='Você é um assistente virtual útil.', verbose_name='System Prompt')),
                ('context_prompt', models.TextField(blank=True, help_text='Informações adicionais sobre o negócio, cardápio, etc.', verbose_name='Contexto Adicional')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('draft', 'Rascunho')], default='draft', max_length=20, verbose_name='Status')),
                ('use_memory', models.BooleanField(default=True, verbose_name='Usar Memória')),
                ('memory_ttl', models.PositiveIntegerField(default=3600, help_text='Tempo que as conversas ficam armazenadas no Redis', verbose_name='TTL da Memória (segundos)')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'db_table': 'agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Session ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='Contagem de Mensagens')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Última Mensagem')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.agent', verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Conversa do Agente',
                'verbose_name_plural': 'Conversas dos Agentes',
                'db_table': 'agent_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=20, verbose_name='Papel')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tokens Usados')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (ms)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agentconversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem do Agente',
                'verbose_name_plural': 'Mensagens dos Agentes',
                'db_table': 'agent_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
