# Generated by Django 4.2.27 on 2026-02-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # This migration previously duplicated the operations in 0002_add_fields.
    # Convert it into a no-op merge entry that depends on the real 0002_add_fields
    # so the migration graph is linear and operations are not applied twice.
    initial = False

    dependencies = [
        ('agents', '0001_initial'),
        ('agents', '0002_add_fields'),
    ]

    operations = []
