# Generated by Django 4.2.28 on 2026-02-08 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('agents', '0001_initial'),
        ('conversations', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='whatsapp_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='conversations.conversation', verbose_name='Conversa WhatsApp'),
        ),
        migrations.AddField(
            model_name='agent',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='agents', to='whatsapp.whatsappaccount', verbose_name='Contas WhatsApp'),
        ),
    ]
