# Generated by Django 4.2.28 on 2026-02-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='provider',
            field=models.CharField(
                choices=[
                    ('kimi', 'Kimi (Moonshot)'),
                    ('openai', 'OpenAI'),
                    ('anthropic', 'Anthropic'),
                    ('ollama', 'Ollama (Local)'),
                    ('nvidia', 'NVIDIA AI')
                ],
                default='kimi',
                max_length=20,
                verbose_name='Provedor'
            ),
        ),
    ]
