# Generated by Django 4.2.27 on 2026-03-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_add_nvidia_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='max_context_messages',
            field=models.PositiveIntegerField(
                default=10,
                help_text='Número máximo de mensagens históricas para manter no contexto',
                verbose_name='Máximo de mensagens de contexto',
            ),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID do Usuário'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='memory_ttl',
            field=models.PositiveIntegerField(
                default=86400,
                help_text='Tempo que as conversas ficam armazenadas no Redis (padrão: 24h)',
                verbose_name='TTL da Memória (segundos)',
            ),
        ),
    ]
