# Generated by Django 4.2.30 on 2026-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_max_context_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='base_url',
            field=models.URLField(blank=True, default='https://api.anthropic.com', verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(default='claude-sonnet-4-6', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='provider',
            field=models.CharField(choices=[('kimi', 'Kimi (Moonshot)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (Local)'), ('nvidia', 'NVIDIA AI')], default='anthropic', max_length=20, verbose_name='Provedor'),
        ),
    ]
