# Generated by Django 4.2.30 on 2026-05-12 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_storecustomeraddress'),
        ('agents', '0007_alter_agent_base_url_alter_agent_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKnowledgeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(choices=[('cardapio', 'Cardápio / Preços'), ('entrega', 'Entrega / Frete'), ('pedido', 'Fluxo de Pedido'), ('pagamento', 'Pagamento / PIX'), ('saudacao', 'Saudação'), ('reclamacao', 'Reclamação'), ('indisponivel', 'Produto Indisponível'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tópico')),
                ('example_input', models.TextField(verbose_name='Exemplo de mensagem do cliente')),
                ('example_response', models.TextField(verbose_name='Exemplo de boa resposta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionais')),
                ('confidence', models.FloatField(default=1.0, help_text='Quanto confiamos neste padrão — decrements por má avaliação', verbose_name='Confiança (0-1)')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Vezes injetado')),
                ('source', models.CharField(choices=[('manual', 'Criado manualmente'), ('auto', 'Extraído automaticamente'), ('reviewed', 'Revisado pelo humano')], default='auto', max_length=20, verbose_name='Origem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='agents.agent', verbose_name='Agente')),
                ('store', models.ForeignKey(blank=True, help_text='Nulo = vale para todos os stores deste agente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_knowledge', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Conhecimento Aprendido',
                'verbose_name_plural': 'Conhecimentos Aprendidos',
                'db_table': 'agent_knowledge_entries',
                'ordering': ['-confidence', '-usage_count'],
                'indexes': [models.Index(fields=['agent', 'is_active'], name='know_agent_active_idx'), models.Index(fields=['agent', 'store', 'topic'], name='know_agent_store_topic_idx')],
            },
        ),
    ]
