# Generated by Django 5.2.15 on 2026-06-17 18:29
# Índice CONCURRENTLY (agent_conversations cresce com cada conversa). atomic=False
# é obrigatório p/ CREATE INDEX CONCURRENTLY.
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('agents', '0008_agent_knowledge_entry'),
        ('conversations', '0006_conversation_contact_profile_fields'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='agentconversation',
            index=models.Index(fields=['agent', 'phone_number', '-last_message_at'], name='agconv_agent_phone_idx'),
        ),
    ]
