# Generated by Django 5.2.17 on 2026-10-06 16:57

from django.db import migrations, models


def desligar_aprendizado_antigo(apps, schema_editor):
    """Os exemplos extraídos sozinhos até 06/10 ensinavam promoção velha,
    resposta de erro e conversa pessoal. Ficam guardados, só saem do ar."""
    Entrada = apps.get_model('agents', 'AgentKnowledgeEntry')
    Entrada.objects.filter(source='auto', is_active=True).update(is_active=False)


def religar(apps, schema_editor):
    Entrada = apps.get_model('agents', 'AgentKnowledgeEntry')
    Entrada.objects.filter(source='auto').update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentconversation_agconv_agent_phone_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentknowledgeentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Criado manualmente'), ('auto', 'Extraído automaticamente'), ('reviewed', 'Revisado pelo humano'), ('sugestao', 'Sugerido pelo atendimento (aguardando aprovação)')], default='auto', max_length=20, verbose_name='Origem'),
        ),
        migrations.RunPython(desligar_aprendizado_antigo, religar),
    ]
