# Generated by Django 4.2.27 on 2026-01-26 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='Display name for this account', max_length=255)),
                ('instagram_account_id', models.CharField(db_index=True, help_text='Instagram Business Account ID (IGBA ID)', max_length=50, unique=True)),
                ('instagram_user_id', models.CharField(db_index=True, help_text='Instagram User ID', max_length=50)),
                ('facebook_page_id', models.CharField(db_index=True, help_text='Connected Facebook Page ID', max_length=50)),
                ('username', models.CharField(help_text='Instagram @username', max_length=100)),
                ('app_id', models.CharField(help_text='Instagram App ID', max_length=50)),
                ('app_secret_encrypted', models.TextField(help_text='Encrypted App Secret')),
                ('access_token_encrypted', models.TextField(help_text='Encrypted access token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Verification'), ('expired', 'Token Expired')], default='pending', max_length=20)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255)),
                ('messaging_enabled', models.BooleanField(default=True)),
                ('auto_response_enabled', models.BooleanField(default=False)),
                ('human_handoff_enabled', models.BooleanField(default=True)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
                'db_table': 'instagram_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('participant_id', models.CharField(db_index=True, max_length=50)),
                ('participant_username', models.CharField(blank=True, max_length=100)),
                ('participant_name', models.CharField(blank=True, max_length=255)),
                ('participant_profile_pic', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='instagram.instagramaccount')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ig_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Conversation',
                'verbose_name_plural': 'Instagram Conversations',
                'db_table': 'instagram_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('instagram_message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (received)'), ('outbound', 'Outbound (sent)')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('share', 'Share (Post/Reel/Story)'), ('story_mention', 'Story Mention'), ('story_reply', 'Story Reply'), ('reaction', 'Reaction'), ('deleted', 'Deleted'), ('unknown', 'Unknown')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sender_id', models.CharField(db_index=True, max_length=50)),
                ('recipient_id', models.CharField(db_index=True, max_length=50)),
                ('text_content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('shared_media_id', models.CharField(blank=True, max_length=100)),
                ('shared_media_url', models.URLField(blank=True)),
                ('reply_to_message_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instagram.instagramaccount')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instagram.instagramconversation')),
            ],
            options={
                'verbose_name': 'Instagram Message',
                'verbose_name_plural': 'Instagram Messages',
                'db_table': 'instagram_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('messages', 'Messages'), ('messaging_postbacks', 'Messaging Postbacks'), ('messaging_seen', 'Messaging Seen'), ('messaging_referral', 'Messaging Referral'), ('comments', 'Comments'), ('unknown', 'Unknown')], max_length=30)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='instagram.instagramaccount')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='instagram.instagrammessage')),
            ],
            options={
                'verbose_name': 'Instagram Webhook Event',
                'verbose_name_plural': 'Instagram Webhook Events',
                'db_table': 'instagram_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processing_status', '-created_at'], name='instagram_w_process_a96699_idx'), models.Index(fields=['event_type', '-created_at'], name='instagram_w_event_t_da26fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['conversation', '-created_at'], name='instagram_m_convers_662027_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['account', 'sender_id', '-created_at'], name='instagram_m_account_ce0e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['status', '-created_at'], name='instagram_m_status_48edb8_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramconversation',
            index=models.Index(fields=['account', 'status', '-last_message_at'], name='instagram_c_account_cc5d06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagramconversation',
            unique_together={('account', 'participant_id')},
        ),
    ]
