# Generated by Django 4.2.30 on 2026-04-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_instagramaccount_page_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='access_token',
            field=models.TextField(help_text='User Access Token ou Instagram Business Token (leitura de mídia, insights).'),
        ),
    ]
