# Generated by Django 4.2.30 on 2026-05-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_instagramaccount_default_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
