# Generated by Django 5.2.17 on 2026-09-21 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_encrypt_instagram_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaDeComentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CUPOM', 'Cupom para quem comentar'), ('SORTEIO', 'Sorteio entre quem comentar')], default='CUPOM', max_length=10)),
                ('media_id', models.CharField(db_index=True, max_length=255)),
                ('palavra_chave', models.CharField(blank=True, default='', max_length=80)),
                ('exige_marcar_amigos', models.PositiveSmallIntegerField(default=0)),
                ('exige_seguir', models.BooleanField(default=False)),
                ('mensagem_dm', models.TextField()),
                ('resposta_publica', models.CharField(blank=True, default='', max_length=300)),
                ('comeca_em', models.DateTimeField(blank=True, null=True)),
                ('termina_em', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_de_comentario', to='instagram.instagramaccount')),
            ],
            options={
                'db_table': 'instagram_campanhas_de_comentario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoNoComentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_id', models.CharField(max_length=255)),
                ('usuario_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('texto', models.TextField(blank=True, default='')),
                ('amigos_marcados', models.PositiveSmallIntegerField(default=0)),
                ('aceita', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, default='', max_length=40)),
                ('dm_enviada', models.BooleanField(default=False)),
                ('erro_da_dm', models.CharField(blank=True, default='', max_length=200)),
                ('ganhador', models.BooleanField(default=False)),
                ('sorteado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='instagram.campanhadecomentario')),
            ],
            options={
                'db_table': 'instagram_participacoes_no_comentario',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campanha', 'comment_id'), name='participacao_unica_por_comentario')],
            },
        ),
    ]
