# Generated by Django 5.2.17 on 2026-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_campanhadecomentario_participacaonocomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='token_invalido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
