# Generated by Django 4.2.28 on 2026-03-02 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import')], max_length=20, verbose_name='action')),
                ('entity_type', models.CharField(blank=True, help_text='e.g., Order, Product, User', max_length=100, verbose_name='entity type')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='entity id')),
                ('entity_repr', models.CharField(blank=True, help_text='String representation of the entity', max_length=255, verbose_name='entity representation')),
                ('previous_data', models.JSONField(blank=True, null=True, verbose_name='previous data')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='new data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='request path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_v2', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_v2_aud_user_id_2ac98e_idx'), models.Index(fields=['action', 'created_at'], name='core_v2_aud_action_5919bd_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_v2_aud_entity__eabf75_idx'), models.Index(fields=['entity_type', 'created_at'], name='core_v2_aud_entity__e299ce_idx')],
            },
        ),
    ]
