# Generated by Django 4.2.28 on 2026-02-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('json_definition', models.JSONField(default=dict, help_text='Estrutura do flow conforme documentação do Meta', verbose_name='Definição JSON')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado'), ('deprecated', 'Descontinuado')], default='draft', max_length=20, verbose_name='Status')),
                ('flow_id', models.CharField(blank=True, help_text='ID do flow na API do WhatsApp Business', max_length=255, null=True, verbose_name='Flow ID (Meta)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
                'db_table': 'whatsapp_flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('waba_id', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('display_phone_number', models.CharField(blank=True, max_length=30)),
                ('access_token_encrypted', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Verification')], default='pending', max_length=20)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255)),
                ('auto_response_enabled', models.BooleanField(default=True)),
                ('human_handoff_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('default_agent', models.ForeignKey(blank=True, help_text='Agente IA padrão para respostas automáticas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_accounts', to='agents.agent')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
                'verbose_name_plural': 'WhatsApp Accounts',
                'db_table': 'whatsapp_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('whatsapp_message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive'), ('template', 'Template'), ('reaction', 'Reaction'), ('button', 'Button'), ('order', 'Order'), ('system', 'System'), ('unknown', 'Unknown')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('from_number', models.CharField(db_index=True, max_length=20)),
                ('to_number', models.CharField(db_index=True, max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('text_body', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=100)),
                ('media_url', models.URLField(blank=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100)),
                ('media_sha256', models.CharField(blank=True, max_length=64)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('template_language', models.CharField(blank=True, max_length=10)),
                ('context_message_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_by_agent', models.BooleanField(default=False, help_text='Processado pelo agente IA')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappaccount')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_number', models.CharField(max_length=20, verbose_name='Número do remetente')),
                ('flow_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Mensagem')),
                ('response_data', models.JSONField(default=dict, verbose_name='Dados da Resposta')),
                ('raw_webhook_data', models.JSONField(default=dict, verbose_name='Dados Brutos do Webhook')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Completo'), ('expired', 'Expirado'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('final_screen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Final')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='whatsapp.flow', verbose_name='Flow')),
            ],
            options={
                'verbose_name': 'Resposta de Flow',
                'verbose_name_plural': 'Respostas de Flows',
                'db_table': 'whatsapp_flow_responses',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='whatsapp.whatsappaccount', verbose_name='Conta WhatsApp'),
        ),
        migrations.AddField(
            model_name='flow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flows', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('message', 'Message'), ('status', 'Status Update'), ('error', 'Error'), ('unknown', 'Unknown')], max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='whatsapp.whatsappaccount')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='whatsapp.message')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'whatsapp_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processing_status', '-created_at'], name='whatsapp_we_process_cad246_idx'), models.Index(fields=['event_type', '-created_at'], name='whatsapp_we_event_t_053ffa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('template_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='pt_BR', max_length=10)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('components', models.JSONField(default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'db_table': 'whatsapp_templates',
                'unique_together': {('account', 'name', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', 'from_number', '-created_at'], name='whatsapp_me_account_22e9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', 'to_number', '-created_at'], name='whatsapp_me_account_d3e247_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', '-created_at'], name='whatsapp_me_status_9b76f6_idx'),
        ),
        migrations.AddIndex(
            model_name='flowresponse',
            index=models.Index(fields=['flow', 'status'], name='whatsapp_fl_flow_id_1c228b_idx'),
        ),
        migrations.AddIndex(
            model_name='flowresponse',
            index=models.Index(fields=['from_number', 'status'], name='whatsapp_fl_from_nu_1e2459_idx'),
        ),
        migrations.AddIndex(
            model_name='flowresponse',
            index=models.Index(fields=['flow_message_id'], name='whatsapp_fl_flow_me_c0a2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['flow_id'], name='whatsapp_fl_flow_id_a94db0_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['status'], name='whatsapp_fl_status_7a1534_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['account', 'status'], name='whatsapp_fl_account_1c2af2_idx'),
        ),
    ]
