# Generated by Django 4.2.28 on 2026-02-09 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContext',
            fields=[
                ('quoted_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Mensagem Citada')),
                ('quoted_message_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo da Mensagem Citada')),
                ('quoted_message_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo da Mensagem Citada')),
                ('quoted_sender_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Remetente Original')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='É Encaminhada')),
                ('forwarded_count', models.PositiveIntegerField(default=0, verbose_name='Número de Encaminhamentos')),
                ('is_frequently_forwarded', models.BooleanField(default=False, verbose_name='Frequentemente Encaminhada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'db_table': 'whatsapp_message_contexts',
                'verbose_name': 'Contexto de Mensagem',
                'verbose_name_plural': 'Contextos de Mensagens',
                'indexes': [
                    models.Index(fields=['quoted_message_id'], name='wh_msgctx_quoted_id_idx'),
                    models.Index(fields=['is_forwarded'], name='wh_msgctx_is_forwarded_idx'),
                    models.Index(fields=['is_frequently_forwarded'], name='wh_msgctx_is_freq_fwd_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='whatsapp.whatsappaccount', verbose_name='Conta')),
                ('messages_sent', models.PositiveIntegerField(default=0, verbose_name='Mensagens Enviadas')),
                ('messages_delivered', models.PositiveIntegerField(default=0, verbose_name='Mensagens Entregues')),
                ('messages_read', models.PositiveIntegerField(default=0, verbose_name='Mensagens Lidas')),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Entrega %')),
                ('read_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Leitura %')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Total')),
                ('marketing_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Marketing')),
                ('utility_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Utilidade')),
                ('authentication_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Autenticação')),
                ('service_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Serviço')),
                ('quality_rating', models.CharField(blank=True, max_length=20, null=True, verbose_name='Qualidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'db_table': 'whatsapp_analytics',
                'verbose_name': 'Analytics do WhatsApp',
                'verbose_name_plural': 'Analytics do WhatsApp',
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
                'indexes': [
                    models.Index(fields=['account', 'date'], name='wh_analytics_account_date_idx'),
                    models.Index(fields=['date'], name='wh_analytics_date_idx'),
                    models.Index(fields=['quality_rating'], name='wh_analytics_quality_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AdvancedTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('template_type', models.CharField(choices=[('carousel', 'Carrossel'), ('lto', 'Limited Time Offer (Cupom)'), ('auth', 'Autenticação (OTP)'), ('order', 'Detalhes de Pedido'), ('catalog', 'Catálogo')], max_length=20, verbose_name='Tipo de Template')),
                ('config', models.JSONField(default=dict, verbose_name='Configuração')),
                ('components', models.JSONField(default=list, verbose_name='Componentes')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='draft', max_length=20, verbose_name='Status')),
                ('meta_template_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID no Meta')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_templates', to='whatsapp.whatsappaccount', verbose_name='Conta WhatsApp')),
                ('language', models.CharField(default='pt_BR', max_length=10, verbose_name='Idioma')),
                ('category', models.CharField(default='MARKETING', max_length=20, verbose_name='Categoria')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submetido em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
            ],
            options={
                'db_table': 'whatsapp_advanced_templates',
                'verbose_name': 'Template Avançado',
                'verbose_name_plural': 'Templates Avançados',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['template_type', 'status'], name='wh_advtemp_type_status_idx'),
                    models.Index(fields=['account', 'status'], name='wh_advtemp_account_status_idx'),
                    models.Index(fields=['meta_template_id'], name='wh_advtemp_meta_id_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AdvancedTemplateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='whatsapp.advancedtemplate', verbose_name='Template')),
                ('to_number', models.CharField(max_length=20, verbose_name='Número')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Mensagem')),
                ('sent_data', models.JSONField(default=dict, verbose_name='Dados Enviados')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'db_table': 'whatsapp_advanced_template_logs',
                'verbose_name': 'Log de Template Avançado',
                'verbose_name_plural': 'Logs de Templates Avançados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('report_type', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, verbose_name='Tipo de Relatório')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('archived', 'Arquivado')], default='active', max_length=20, verbose_name='Status')),
                ('accounts', models.ManyToManyField(related_name='analytics_reports', to='whatsapp.whatsappaccount', verbose_name='Contas')),
                ('include_conversations', models.BooleanField(default=True, verbose_name='Incluir Conversações')),
                ('include_messages', models.BooleanField(default=True, verbose_name='Incluir Mensagens')),
                ('include_costs', models.BooleanField(default=True, verbose_name='Incluir Custos')),
                ('include_quality', models.BooleanField(default=True, verbose_name='Incluir Qualidade')),
                ('recipients', models.JSONField(default=list, verbose_name='Destinatários')),
                ('schedule_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dia do Agendamento')),
                ('schedule_time', models.TimeField(default='08:00', verbose_name='Horário')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('last_run_status', models.CharField(blank=True, max_length=20, verbose_name='Status da Última Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'db_table': 'whatsapp_analytics_reports',
                'verbose_name': 'Relatório de Analytics',
                'verbose_name_plural': 'Relatórios de Analytics',
                'ordering': ['-created_at'],
            },
        ),
    ]