# Generated by Django 4.2.27 on 2026-01-11 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Cart',
                'verbose_name_plural': 'Store Carts',
                'db_table': 'store_carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/combos/')),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('track_stock', models.BooleanField(default=False)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Combo',
                'verbose_name_plural': 'Store Combos',
                'db_table': 'store_combos',
                'ordering': ['store', '-created_at'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StoreComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('allow_customization', models.BooleanField(default=False)),
                ('customization_options', models.JSONField(blank=True, default=dict)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.storecombo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='stores.storeproduct')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storeproductvariant')),
            ],
            options={
                'verbose_name': 'Combo Item',
                'verbose_name_plural': 'Combo Items',
                'db_table': 'store_combo_items',
            },
        ),
        migrations.CreateModel(
            name='StoreCartComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customizations', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='stores.storecart')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stores.storecombo')),
            ],
            options={
                'verbose_name': 'Cart Combo Item',
                'verbose_name_plural': 'Cart Combo Items',
                'db_table': 'store_cart_combo_items',
            },
        ),
        migrations.CreateModel(
            name='StoreProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/product_types/')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Custom field definitions for products of this type')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='stores.store')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'db_table': 'store_product_types',
                'ordering': ['store', 'sort_order', 'name'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StoreCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.storecart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stores.storeproduct')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='stores.storeproductvariant')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'store_cart_items',
                'unique_together': {('cart', 'product', 'variant')},
            },
        ),
        migrations.AddIndex(
            model_name='storecart',
            index=models.Index(fields=['store', 'user'], name='store_carts_store_i_e34206_idx'),
        ),
        migrations.AddIndex(
            model_name='storecart',
            index=models.Index(fields=['store', 'session_key'], name='store_carts_store_i_5ce7ab_idx'),
        ),
    ]
