# Generated by Django 4.2.30 on 2026-05-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('agents', '0006_agent_max_context_messages_and_more'),
    ]

    operations = [
        # URLs for business
        migrations.AddField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, help_text='Website URL'),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_url',
            field=models.URLField(blank=True, help_text='Menu/catalog URL'),
        ),
        migrations.AddField(
            model_name='store',
            name='order_url',
            field=models.URLField(blank=True, help_text='Order URL'),
        ),
        # Automation settings
        migrations.AddField(
            model_name='store',
            name='auto_reply_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='welcome_message_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_auto_send',
            field=models.BooleanField(default=True, help_text='Auto-send menu when requested'),
        ),
        migrations.AddField(
            model_name='store',
            name='abandoned_cart_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='abandoned_cart_delay_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='store',
            name='pix_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_confirmation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='order_status_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='use_ai_agent',
            field=models.BooleanField(default=True, help_text='Use AI agent for customer interactions'),
        ),
        migrations.AddField(
            model_name='store',
            name='default_agent',
            field=models.ForeignKey(blank=True, help_text='Default AI agent for customer interactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='agents.agent'),
        ),
    ]
