# Generated by Django 4.2.27 on 2026-03-26 16:31

import apps.core.fields
import apps.stores.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_cart_combo_virtual_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='stores/banners/', validators=[apps.stores.models.base._validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/', validators=[apps.stores.models.base._validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='access_token',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Access Token (encrypted)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='api_key',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='API Key (encrypted)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='api_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='API Secret (encrypted)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='public_key',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Public Key (encrypted)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='webhook_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Webhook Secret (encrypted)', max_length=1000),
        ),
    ]
