# Generated by Django 4.2.30 on 2026-04-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_order_external_delivery_provider'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'status'], name='store_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status', 'is_active'], name='store_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storecart',
            index=models.Index(fields=['user', 'store', 'is_active'], name='cart_user_store_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storecustomer',
            index=models.Index(fields=['phone'], name='customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['customer', 'store'], name='order_customer_store_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'created_at'], name='order_store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['store', 'category', 'status'], name='product_store_cat_status_idx'),
        ),
    ]
