# Generated by Django 4.2.30 on 2026-04-20 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_store_owner_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePrintAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('station', models.CharField(default='kitchen', max_length=50)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS'), ('other', 'Other')], default='windows', max_length=20)),
                ('connection_mode', models.CharField(choices=[('windows_printer', 'Windows Printer'), ('usb_direct', 'USB Direct'), ('network', 'Network')], default='windows_printer', max_length=30)),
                ('printer_name', models.CharField(blank=True, max_length=255)),
                ('printer_host', models.CharField(blank=True, max_length=255)),
                ('printer_port', models.PositiveIntegerField(default=9100)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=2)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('api_key_prefix', models.CharField(db_index=True, max_length=32, unique=True)),
                ('api_key_hash', models.CharField(max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('host_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_agents', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Print Agent',
                'verbose_name_plural': 'Store Print Agents',
                'db_table': 'store_print_agents',
            },
        ),
        migrations.CreateModel(
            name='StorePrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('station', models.CharField(default='kitchen', max_length=50)),
                ('template', models.CharField(choices=[('kitchen_ticket', 'Kitchen Ticket'), ('customer_receipt', 'Customer Receipt')], default='kitchen_ticket', max_length=40)),
                ('source', models.CharField(choices=[('order_created', 'Order Created'), ('manual_reprint', 'Manual Reprint'), ('test', 'Test')], default='order_created', max_length=30)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('printer_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_jobs', to='stores.storeprintagent')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='stores.storeorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Print Job',
                'verbose_name_plural': 'Store Print Jobs',
                'db_table': 'store_print_jobs',
                'indexes': [models.Index(fields=['store', 'status', 'available_at'], name='pr_job_store_status_idx'), models.Index(fields=['store', 'station', 'status'], name='pr_job_store_station_idx'), models.Index(fields=['order', 'template'], name='print_job_order_template_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='storeprintjob',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='store_print_job_dedupe_key_unique'),
        ),
        migrations.AddIndex(
            model_name='storeprintagent',
            index=models.Index(fields=['store', 'status'], name='print_agent_store_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storeprintagent',
            index=models.Index(fields=['store', 'station'], name='print_agent_store_station_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeprintagent',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='store_print_agent_slug_unique'),
        ),
    ]
