# Generated by Django 4.2.30 on 2026-05-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_storeprintagent_storeprintjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprintjob',
            name='target_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='stores.storeprintagent'),
        ),
    ]
