# Generated by Django 4.2.30 on 2026-05-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unifieduser_django_user'),
        ('stores', '0011_storecustomeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecustomer',
            name='unified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_customers', to='users.unifieduser', verbose_name='Identidade Universal'),
        ),
    ]
