# Generated by Django 4.2.27 on 2026-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_add_order_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Secure token for public order access (payment page, tracking)', max_length=64, unique=True),
        ),
    ]
