# Generated by Django 5.2.14 on 2026-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_unique_active_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Domínio próprio da loja (ex: cesaladas.com.br)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='template',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('bold', 'Bold'), ('classic', 'Classic')], default='fresh', help_text='Layout template do storefront', max_length=20),
        ),
    ]
