# Generated by Django 4.2.27 on 2026-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_merge_wishlist_conflict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storewishlist',
            options={'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist Items'},
        ),
        migrations.RemoveField(
            model_name='storewishlist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='storecombo',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storecoupon',
            name='applicable_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='storecoupon',
            name='applicable_products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='storedeliveryzone',
            name='color',
            field=models.CharField(default='#722F37', max_length=7),
        ),
        migrations.AlterField(
            model_name='storedeliveryzone',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Secure token for public order access', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='pix_ticket_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='storewishlist',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
