# Generated by Django 5.2.14 on 2026-05-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_store_storefront_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Slogan curto exibido no storefront', max_length=200),
        ),
    ]
