# Generated by Django 5.2.14 on 2026-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_store_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprintagent',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
