# Generated by Django 5.2.14 on 2026-05-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_storeprintagent_poll_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='pix_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
