# Generated by Django 5.2.14 on 2026-05-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_add_pix_expires_at_to_store_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='abandoned_cart_delay_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='store',
            name='abandoned_cart_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='auto_reply_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_auto_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='order_status_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_confirmation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='pix_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='use_ai_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='welcome_message_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
