# Generated by Django 4.2.27 on 2026-01-31 22:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_add_payment_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_order_i_828eb1_idx',
            old_name='stores_stpay_order_i_9b6c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_externa_7fa6e1_idx',
            old_name='stores_stpay_externa_2e7f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_gateway_58fd21_idx',
            old_name='stores_stpay_gateway_4c8d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_status_397da8_idx',
            old_name='stores_stpay_status__5a9e1b_idx',
        ),
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_payment_d3e9da_idx',
            old_name='stores_stpay_payment_6b2f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentgateway',
            new_name='store_payme_store_i_a8a59f_idx',
            old_name='stores_stpay_store_i_7f3f6b_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentgateway',
            new_name='store_payme_store_i_3e845d_idx',
            old_name='stores_stpay_store_i_8a4e2c_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentgateway',
            new_name='store_payme_gateway_817878_idx',
            old_name='stores_stpay_gateway_3d5a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentwebhookevent',
            new_name='store_payme_gateway_9d9c34_idx',
            old_name='stores_stpay_gateway_7d3a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentwebhookevent',
            new_name='store_payme_process_3e42df_idx',
            old_name='stores_stpay_processi_8e4b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentwebhookevent',
            new_name='store_payme_event_i_c15881_idx',
            old_name='stores_stpay_event_i_9f5c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentwebhookevent',
            new_name='store_payme_payment_4e9eb5_idx',
            old_name='stores_stpay_payment_a1b6d2_idx',
        ),
        migrations.AddField(
            model_name='storepaymentwebhookevent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
    ]
