# Generated by Django 5.2.14 on 2026-05-28 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_add_automation_fields_to_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (staff)'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='manual_discount_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo do Desconto'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='manual_discount_type',
            field=models.CharField(blank=True, choices=[('percent', '%'), ('fixed', 'R$')], max_length=10, null=True, verbose_name='Tipo de Desconto Manual'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='manual_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do Desconto Manual'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='surcharge_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo do Acréscimo'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='surcharge_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do Acréscimo'),
        ),
        migrations.CreateModel(
            name='StoreTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gerente'), ('operator', 'Operador'), ('viewer', 'Visualizador')], db_index=True, default='operator', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por')),
                ('tenant', models.ForeignKey(help_text='The tenant/store this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'db_table': 'store_team_members',
                'indexes': [models.Index(fields=['tenant', 'role'], name='store_team__tenant__827fe8_idx'), models.Index(fields=['user', 'is_active'], name='store_team__user_id_c60522_idx')],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
