# Generated by Django 4.2.27 on 2026-01-31 23:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_fix_payment_model_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storepaymentwebhookevent',
            name='store_pay_webhook_gateway_idx',
        ),
        migrations.RemoveIndex(
            model_name='storepaymentwebhookevent',
            name='store_pay_webhook_event_idx',
        ),
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_order_i_828eb1_idx',
            old_name='store_pay_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_externa_7fa6e1_idx',
            old_name='store_pay_external_idx',
        ),
        migrations.RenameIndex(
            model_name='storepayment',
            new_name='store_payme_gateway_58fd21_idx',
            old_name='store_pay_gateway_status_idx',
        ),
        migrations.RenameIndex(
            model_name='storepaymentgateway',
            new_name='store_payme_store_i_a8a59f_idx',
            old_name='store_pay_gateway_store_idx',
        ),
        migrations.RemoveField(
            model_name='storepayment',
            name='external_url',
        ),
        migrations.AddField(
            model_name='storepayment',
            name='barcode',
            field=models.CharField(blank=True, help_text='Boleto barcode', max_length=255),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error code if failed', max_length=50),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Payment expiration', null=True),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External reference (order number)', max_length=255),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gateway fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount after fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='payer_document',
            field=models.CharField(blank=True, help_text='CPF/CNPJ', max_length=50),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='payer_email',
            field=models.EmailField(blank=True, help_text='Payer email', max_length=254),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Payer name', max_length=255),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='payment_id',
            field=models.CharField(db_index=True, default='', help_text='Internal payment ID (UUID)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Payment URL for customer'),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='qr_code',
            field=models.TextField(blank=True, help_text='PIX QR code text'),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='qr_code_base64',
            field=models.TextField(blank=True, help_text='PIX QR code base64 image'),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total refunded amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='storepayment',
            name='ticket_url',
            field=models.URLField(blank=True, help_text='Boleto/PDF URL'),
        ),
        migrations.AddField(
            model_name='storepaymentwebhookevent',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Request headers'),
        ),
        migrations.AddField(
            model_name='storepaymentwebhookevent',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Related order (if identified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_webhook_events', to='stores.storeorder'),
        ),
        migrations.AddField(
            model_name='storepaymentwebhookevent',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='currency',
            field=models.CharField(default='BRL', help_text='Currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if failed'),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External payment ID (from gateway)', max_length=255),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text='Payment gateway used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='stores.storepaymentgateway'),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Full gateway response'),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='order',
            field=models.ForeignKey(help_text='Order this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stores.storeorder'),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet'), ('other', 'Other')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='event_id',
            field=models.CharField(db_index=True, help_text='External event ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='event_type',
            field=models.CharField(help_text='Event type (e.g., payment.created)', max_length=100),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='gateway',
            field=models.ForeignKey(help_text='Gateway that received this event', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='stores.storepaymentgateway'),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='payload',
            field=models.JSONField(help_text='Full webhook payload'),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Related payment (if identified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='stores.storepayment'),
        ),
        migrations.AlterField(
            model_name='storepaymentwebhookevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='storepayment',
            index=models.Index(fields=['status', 'created_at'], name='store_payme_status_397da8_idx'),
        ),
        migrations.AddIndex(
            model_name='storepayment',
            index=models.Index(fields=['payment_method', 'status'], name='store_payme_payment_d3e9da_idx'),
        ),
        migrations.AddIndex(
            model_name='storepaymentgateway',
            index=models.Index(fields=['store', 'gateway_type'], name='store_payme_store_i_3e845d_idx'),
        ),
        migrations.AddIndex(
            model_name='storepaymentgateway',
            index=models.Index(fields=['gateway_type', 'is_enabled'], name='store_payme_gateway_817878_idx'),
        ),
        migrations.AddIndex(
            model_name='storepaymentwebhookevent',
            index=models.Index(fields=['gateway', 'event_type'], name='store_payme_gateway_9d9c34_idx'),
        ),
        migrations.AddIndex(
            model_name='storepaymentwebhookevent',
            index=models.Index(fields=['processing_status', 'created_at'], name='store_payme_process_3e42df_idx'),
        ),
        migrations.AddIndex(
            model_name='storepaymentwebhookevent',
            index=models.Index(fields=['event_id', 'gateway'], name='store_payme_event_i_c15881_idx'),
        ),
        migrations.AddIndex(
            model_name='storepaymentwebhookevent',
            index=models.Index(fields=['payment', 'event_type'], name='store_payme_payment_4e9eb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='storepaymentgateway',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('store', 'gateway_type'), name='unique_gateway_type_per_store'),
        ),
        migrations.AddConstraint(
            model_name='storepaymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('gateway', 'event_id'), name='unique_event_per_gateway'),
        ),
    ]
