# Generated by Django 4.2 on 2026-02-02 04:30

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge migration to resolve conflict between:
    - 0017_add_whatsapp_account_to_store
    - 0017_add_payment_models
    - 0018_fix_payment_model_ids
    - 0019_remove_storepaymentwebhookevent_store_pay_webhook_gateway_idx_and_more
    """

    dependencies = [
        ('stores', '0017_add_payment_models'),
        ('stores', '0019_remove_storepaymentwebhookevent_store_pay_webhook_gateway_idx_and_more'),
    ]

    operations = [
    ]
