# Generated by Django 4.2 on 2026-02-02 05:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration - fields already exist in database.
    This satisfies Django's migration check without altering database.
    """

    dependencies = [
        ('stores', '0020_merge_conflicts'),
    ]

    operations = [
    ]
