# Generated by Django 5.x on 2026-02-06 21:30
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0022_store_whatsapp_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="whatsapp_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="whatsapp.whatsappaccount",
            ),
        ),
    ]
