# Generated by Django 5.2.14 on 2026-05-29 14:17

from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
            }
        field = model._meta.get_field(self.name)
        if field.column in columns:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_add_uber_delivery_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storeorder',
            new_name='store_order_deliver_f8add8_idx',
            old_name='stores_stor_deliver_a12b3c',
        ),
        migrations.RenameIndex(
            model_name='storeorder',
            new_name='store_order_uber_de_3e343c_idx',
            old_name='stores_stor_uber_de_f4e5d6',
        ),
        AddFieldIfMissing(
            model_name='storeorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfMissing(
            model_name='storeorder',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfMissing(
            model_name='storeorder',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfMissing(
            model_name='storeorder',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfMissing(
            model_name='storeorder',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfMissing(
            model_name='storeorder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='template',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('bold', 'Bold'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('dark', 'Dark')], default='fresh', help_text='Layout template do storefront', max_length=20),
        ),
    ]
