# Generated by Django 6.0.6 on 2026-06-06 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_order_combo_item_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeordercomboitem',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_selections', to='stores.storeorderitem'),
        ),
        migrations.CreateModel(
            name='ComboProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=True)),
                ('min_selections', models.PositiveIntegerField(default=1)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('allow_duplicate_variants', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='stores.storecombo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeproduct')),
            ],
            options={
                'verbose_name': 'Combo Product Group',
                'verbose_name_plural': 'Combo Product Groups',
                'db_table': 'combo_product_groups',
                'ordering': ['position'],
                'unique_together': {('combo', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ComboProductGroupVariantLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_limits', to='stores.comboproductgroup')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeproductvariant')),
            ],
            options={
                'verbose_name': 'Combo Variant Limit',
                'verbose_name_plural': 'Combo Variant Limits',
                'db_table': 'combo_product_group_variant_limits',
                'unique_together': {('group', 'variant')},
            },
        ),
    ]
