# Generated by Django 5.2.15 on 2026-06-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_storecartcomboitem_customizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
