# Generated by Django 5.2.15 on 2026-06-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_storeproduct_paused_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreComboItem',
        ),
    ]
