# Generated by Django 5.2.15 on 2026-06-12 14:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_delete_storecomboitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='stores.storeorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Review',
                'verbose_name_plural': 'Store Reviews',
                'db_table': 'store_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='store_revie_store_i_b4ad91_idx'), models.Index(fields=['store', 'rating'], name='store_revie_store_i_726afe_idx')],
            },
        ),
    ]
