# Generated by Django 5.2.15 on 2026-06-12 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_storereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualified_count', models.PositiveIntegerField(default=0)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_loyalty_accounts',
            },
        ),
        migrations.CreateModel(
            name='StoreLoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('earn', 'Crédito'), ('redeem', 'Resgate'), ('adjust', 'Ajuste manual')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stores.storeloyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='stores.storeorder')),
            ],
            options={
                'db_table': 'store_loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storeloyaltyaccount',
            index=models.Index(fields=['store', 'user'], name='store_loyal_store_i_aedee6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeloyaltyaccount',
            unique_together={('store', 'user')},
        ),
        migrations.AddConstraint(
            model_name='storeloyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'kind'), name='loyalty_unique_order_kind'),
        ),
    ]
