# Generated by Django 5.2.15 on 2026-06-12 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0033_storeloyaltyaccount_storeloyaltytransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('counted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_opened', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='stores.store')),
            ],
            options={
                'db_table': 'store_cash_sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sangria', 'Sangria'), ('reforco', 'Reforço')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stores.storecashsession')),
            ],
            options={
                'db_table': 'store_cash_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='storecashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('store',), name='cash_unique_open_session_per_store'),
        ),
    ]
