# Generated by Django 5.2.15 on 2026-06-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0034_storecashsession_storecashmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprintagent',
            name='available_printers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
