# Generated by Django 5.2.15 on 2026-06-13 17:30

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_storeprintagent_available_printers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepayment',
            name='payer_document',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='CPF/CNPJ (encrypted)', max_length=255),
        ),
    ]
