# Generated by Django 5.2.15 on 2026-06-16 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0039_variant_options_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproductgroup',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comboproductgroup',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.storeproduct'),
        ),
        migrations.CreateModel(
            name='ComboProductGroupProductOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='stores.comboproductgroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeproduct')),
            ],
            options={
                'verbose_name': 'Combo Product Option',
                'verbose_name_plural': 'Combo Product Options',
                'db_table': 'combo_product_group_product_options',
                'ordering': ['position'],
                'unique_together': {('group', 'product')},
            },
        ),
    ]
