# Generated by Django 5.2.15 on 2026-06-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0040_comboproductgroup_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecombo',
            name='dynamic_pricing',
            field=models.BooleanField(default=False),
        ),
    ]
