# Generated by Django 5.2.15 on 2026-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0041_storecombo_dynamic_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Wizard de onboarding concluído (passos mínimos).'),
        ),
        migrations.AddField(
            model_name='store',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], default='starter', help_text='Plano de assinatura (feature-gates aplicados no sub-projeto Billing)', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Fim do trial gratuito (signup self-service). Null = sem trial.', null=True),
        ),
    ]
