# Generated by Django 5.2.15 on 2026-06-17 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0042_store_onboarding_completed_store_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(default='starter', max_length=20)),
                ('status', models.CharField(choices=[('trialing', 'Em trial'), ('active', 'Ativa'), ('past_due', 'Pagamento atrasado'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada')], default='trialing', max_length=20)),
                ('mp_preapproval_id', models.CharField(blank=True, default='', max_length=255)),
                ('setup_fee_paid', models.BooleanField(default=False)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Subscription',
                'verbose_name_plural': 'Store Subscriptions',
                'db_table': 'store_subscriptions',
            },
        ),
    ]
