# Generated by Django 5.2.15 on 2026-06-17 18:29

from django.conf import settings
from django.db import migrations, models


def grandfather_existing_stores(apps, schema_editor):
    """Todas as lojas que já existem (pré-SaaS) ficam isentas de cobrança/limites."""
    Store = apps.get_model('stores', 'Store')
    Store.objects.update(billing_exempt=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0043_storesubscription'),
        ('users', '0003_useraddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='billing_exempt',
            field=models.BooleanField(default=False, help_text='Isenta de cobrança e limites de plano (grandfather: lojas pré-SaaS).'),
        ),
        migrations.RunPython(grandfather_existing_stores, noop_reverse),
        migrations.AddIndex(
            model_name='storecustomer',
            index=models.Index(fields=['whatsapp'], name='customer_whatsapp_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'status', 'created_at'], name='order_store_stat_created_idx'),
        ),
    ]
