# Generated by Django 5.2.15 on 2026-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0044_store_billing_exempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='template',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('bold', 'Bold'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('dark', 'Dark'), ('elegant', 'Elegant')], default='fresh', help_text='Layout template do storefront', max_length=20),
        ),
    ]
