# Generated by Django 5.2.15 on 2026-06-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0045_alter_store_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeproductvariant',
            options={'ordering': ['product', 'sort_order', 'created_at'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
    ]
