# Generated by Django 5.2.15 on 2026-06-25 22:15

import django.db.models.deletion
from django.db import migrations, models


def backfill_store_from_order(apps, schema_editor):
    """Toda cobrança existente tinha order (campo era obrigatório) — popula
    store a partir do pedido para manter o invariante (store sempre presente)."""
    StorePayment = apps.get_model('stores', 'StorePayment')
    StoreOrder = apps.get_model('stores', 'StoreOrder')
    StorePayment.objects.filter(store__isnull=True, order__isnull=False).update(
        store_id=models.Subquery(
            StoreOrder.objects.filter(pk=models.OuterRef('order_id')).values('store_id')[:1]
        )
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0046_alter_storeproductvariant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepayment',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Loja dona da cobrança (obrigatório; inferido do pedido quando há order)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_payments', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this payment belongs to (null para cobrança avulsa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stores.storeorder'),
        ),
        migrations.RunPython(backfill_store_from_order, noop_reverse),
    ]
