# Generated by Django 5.2.15 on 2026-06-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0047_storepayment_store_alter_storepayment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesubscription',
            name='dunning_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storesubscription',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storesubscription',
            name='mp_setup_payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
