# Generated by Django 5.2.15 on 2026-06-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0048_storesubscription_dunning_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='onboarding_wizard_seen',
            field=models.BooleanField(default=False, help_text='True após o dono ver/fechar o wizard de setup a 1ª vez (controla o auto-open).'),
        ),
    ]
