# Generated by Django 5.2.15 on 2026-06-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0048_storesubscription_dunning_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='plan',
            field=models.CharField(choices=[('free', 'Grátis'), ('starter', 'Essencial'), ('pro', 'Pro'), ('premium', 'Premium')], default='starter', help_text='Plano de assinatura (feature-gates aplicados no sub-projeto Billing)', max_length=20),
        ),
    ]
