# Generated by Django 5.2.15 on 2026-07-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0049_alter_store_plan'),
        ('stores', '0049_onboarding_wizard_seen'),
    ]

    operations = [
    ]
