# Generated by Django 5.2.15 on 2026-07-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0051_store_owner_protect_payment_store_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='storesubscription',
            name='downgraded_for_nonpayment',
            field=models.BooleanField(default=False),
        ),
    ]
