# Generated by Django 5.2.15 on 2026-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0053_store_meta_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecoupon',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Exibir como banner no cardápio'),
        ),
    ]
