# Generated by Django 5.2.15 on 2026-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0054_storecoupon_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='clarity_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='clarity_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
