# Generated by Django 5.2.16 on 2026-07-28 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0055_store_clarity_enabled_store_clarity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioClickStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('link_key', models.CharField(max_length=64)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_click_stats', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'date'], name='bioclick_store_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'date', 'link_key'), name='bioclick_store_date_key_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StoreBioLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(blank=True, default='', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_links', to='stores.store')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['store', 'is_active'], name='biolink_store_active_idx')],
            },
        ),
    ]
