# Generated by Django 5.2.16 on 2026-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0056_storebiolink_bioclickstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebiolink',
            name='icon_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
