# Generated by Django 5.2.16 on 2026-07-31 16:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0058_storecombo_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='stores.storeproduct')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.storereview')),
            ],
            options={
                'verbose_name': 'Store Product Review',
                'verbose_name_plural': 'Store Product Reviews',
                'db_table': 'store_product_reviews',
                'indexes': [models.Index(fields=['product', 'rating'], name='store_produ_product_cbe29c_idx')],
                'constraints': [models.UniqueConstraint(fields=('review', 'product'), name='uniq_review_product')],
            },
        ),
    ]
