# Generated by Django 5.2.16 on 2026-08-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0060_storeorder_cancel_reason_storeorder_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecoupon',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
