# Generated by Django 5.2.16 on 2026-08-05 23:02

from django.db import migrations, models


def liquidar_pagamento_dos_cancelados(apps, schema_editor):
    """Corrige o histórico: pedido cancelado nunca deveria ter ficado 'paid'.

    Em produção (05/ago/2026) eram 8 pedidos de balcão da loja `pastita`,
    R$ 631,79 contados como faturamento — 22% a mais que a receita real.
    """
    StoreOrder = apps.get_model('stores', 'StoreOrder')
    final = ('refunded', 'partially_refunded', 'cancelled')

    StoreOrder.objects.filter(status='refunded').exclude(
        payment_status__in=final
    ).update(payment_status='refunded')

    StoreOrder.objects.filter(status__in=('cancelled', 'failed')).exclude(
        payment_status__in=final
    ).update(payment_status='cancelled')


def desfazer(apps, schema_editor):
    """Volta para 'paid' só o que tinha dinheiro registrado (paid_at)."""
    StoreOrder = apps.get_model('stores', 'StoreOrder')
    StoreOrder.objects.filter(
        payment_status='cancelled', paid_at__isnull=False
    ).update(payment_status='paid')
    StoreOrder.objects.filter(
        payment_status='cancelled', paid_at__isnull=True
    ).update(payment_status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0061_storecoupon_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RunPython(liquidar_pagamento_dos_cancelados, desfazer),
    ]
