# Generated by Django 5.2.16 on 2026-08-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0062_pagamento_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Entrega'), ('pickup', 'Retirada'), ('digital', 'Entrega digital')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Estornado'), ('partially_refunded', 'Estornado em parte'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('processing', 'Processando'), ('paid', 'Pago'), ('preparing', 'Em preparo'), ('ready', 'Pronto'), ('shipped', 'Despachado'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cash', 'Dinheiro'), ('bank_transfer', 'Transferência bancária'), ('wallet', 'Carteira digital'), ('other', 'Outro')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando'), ('processing', 'Processando'), ('completed', 'Recebido'), ('failed', 'Falhou'), ('cancelled', 'Cancelada'), ('refunded', 'Estornada'), ('partially_refunded', 'Estornada em parte')], db_index=True, default='pending', max_length=20),
        ),
    ]
