# Generated by Django 5.2.16 on 2026-08-09 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0063_traduz_rotulos_de_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='rating_atendimento',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Atendimento'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='rating_comida',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualidade da comida'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='rating_entrega',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tempo de entrega'),
        ),
    ]
