# Generated by Django 5.2.16 on 2026-08-10 16:47

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0064_pilares_de_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentgateway',
            name='connection_type',
            field=models.CharField(choices=[('manual', 'Token colado pelo lojista'), ('oauth', 'Autorizado via OAuth')], default='manual', help_text='manual = token colado; oauth = autorizado pelo lojista', max_length=10),
        ),
        migrations.AddField(
            model_name='storepaymentgateway',
            name='external_account_id',
            field=models.CharField(blank=True, help_text='ID da conta no provedor (user_id do Mercado Pago).', max_length=64),
        ),
        migrations.AddField(
            model_name='storepaymentgateway',
            name='refresh_token',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Refresh token do OAuth (encrypted). Vazio no modo manual.', max_length=1000),
        ),
        migrations.AddField(
            model_name='storepaymentgateway',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Validade do access_token no OAuth. Nulo no modo manual.', null=True),
        ),
    ]
