# Generated by Django 5.2.16 on 2026-08-10 17:46

from django.db import migrations, models


def ligar_nas_lojas_que_ja_existem(apps, schema_editor):
    """Toda loja que existe hoje é do próprio dono.

    Elas já recebem na conta da plataforma desde sempre, com a contabilidade
    dele. Deixar o default False aqui as quebraria — e o default False só faz
    sentido para as lojas que vierem DEPOIS, que podem ser de cliente.
    """
    Store = apps.get_model('stores', 'Store')
    Store.objects.update(usa_gateway_da_plataforma=True)


def desligar(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    Store.objects.update(usa_gateway_da_plataforma=False)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0065_storepaymentgateway_connection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='usa_gateway_da_plataforma',
            field=models.BooleanField(default=False, help_text='Recebe os pagamentos na conta da PLATAFORMA (MERCADO_PAGO_ACCESS_TOKEN). Só para lojas do próprio dono, com contabilidade dele. Loja de cliente fica False e precisa cadastrar a conta dela — do contrário o dinheiro de terceiro passaria pelo CNPJ da plataforma sem contrato.'),
        ),
            migrations.RunPython(ligar_nas_lojas_que_ja_existem, desligar),
    ]
