# Generated by Django 5.2.16 on 2026-08-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0066_recebimento_da_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_remetente',
            field=models.EmailField(blank=True, default='', help_text='Só é usado depois que o domínio for verificado no Resend.', max_length=254, verbose_name='E-mail remetente próprio'),
        ),
        migrations.AddField(
            model_name='store',
            name='remetente_verificado',
            field=models.BooleanField(default=False, help_text='Marque só quando o domínio estiver verificado no provedor de e-mail.', verbose_name='Remetente verificado'),
        ),
    ]
