# Generated by Django 5.2.17 on 2026-08-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0067_remetente_proprio_da_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecombo',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
