# Generated by Django 5.2.17 on 2026-08-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0068_storecombo_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='promo_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], help_text='A promoção vale toda semana neste dia.', null=True, verbose_name='Dia da promoção'),
        ),
    ]
