# Generated by Django 5.2.17 on 2026-08-27 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0070_dominio_vazio_vira_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='builder_expand_variants',
            field=models.BooleanField(default=False, help_text="Cada variante do produto vira uma opção própria — é assim que um único produto 'Molho' oferece seus 4 sabores como escolhas."),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='builder_included',
            field=models.BooleanField(default=False, help_text='Itens deste passo não são cobrados à parte (já inclusos no preço base).'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='builder_max_selections',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantos itens o cliente pode escolher neste passo.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='builder_required',
            field=models.BooleanField(default=False, help_text='O cliente precisa escolher algo aqui para fechar a montagem.'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='builder_step_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Posição desta categoria como passo do montador (0 = primeiro). Vazio significa que a categoria não participa do montador. É independente de `sort_order`, que ordena a vitrine.', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='template',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('bold', 'Bold'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('dark', 'Dark'), ('elegant', 'Elegant'), ('banquete', 'Banquete')], default='fresh', help_text='Layout template do storefront', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='storecategory',
            constraint=models.UniqueConstraint(fields=('store', 'builder_step_order'), name='passo_unico_por_loja_no_montador'),
        ),
    ]
