# Generated by Django 5.2.17 on 2026-09-02 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0073_montador_exige_passo_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCashbackLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('origin', models.CharField(choices=[('purchase', 'Compra própria'), ('referral', 'Indicação'), ('adjust', 'Ajuste manual')], default='purchase', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_lots', to='stores.storeorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_lots', to='stores.store')),
            ],
            options={
                'db_table': 'store_cashback_lots',
                'ordering': ['expires_at', 'created_at'],
                'indexes': [models.Index(fields=['store', 'phone', 'expires_at'], name='store_cashb_store_i_5c4c03_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'origin'), name='cashback_unico_por_pedido_e_origem')],
            },
        ),
        migrations.CreateModel(
            name='StoreCashbackRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_redemptions', to='stores.storeorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_redemptions', to='stores.store')),
            ],
            options={
                'db_table': 'store_cashback_redemptions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order',), name='cashback_resgate_unico_por_pedido')],
            },
        ),
    ]
