# Generated by Django 5.2.17 on 2026-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0074_cashback_por_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecashbacklot',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='storecashbacklot',
            name='origin',
            field=models.CharField(choices=[('purchase', 'Compra própria'), ('referral', 'Indicação'), ('adjust', 'Ajuste manual'), ('prepaid', 'Carteira pré-paga')], default='purchase', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='storecashbacklot',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('store', 'source_ref'), name='cashback_unico_por_cobranca'),
        ),
    ]
