# Generated by Django 5.2.17 on 2026-09-03 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0075_carteira_prepaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDeliveryCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('remaining', models.PositiveIntegerField()),
                ('granted', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_coupons', to='stores.store')),
            ],
            options={
                'db_table': 'store_delivery_coupons',
                'ordering': ['expires_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreDeliveryCouponUse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='stores.storedeliverycoupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_coupon_uses', to='stores.storeorder')),
            ],
            options={
                'db_table': 'store_delivery_coupon_uses',
            },
        ),
        migrations.AddIndex(
            model_name='storedeliverycoupon',
            index=models.Index(fields=['store', 'phone', 'expires_at'], name='store_deliv_store_i_22e947_idx'),
        ),
        migrations.AddConstraint(
            model_name='storedeliverycoupon',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('store', 'source_ref'), name='cupom_entrega_unico_por_cobranca'),
        ),
        migrations.AddConstraint(
            model_name='storedeliverycouponuse',
            constraint=models.UniqueConstraint(fields=('order',), name='cupom_entrega_uso_unico_por_pedido'),
        ),
    ]
