# Generated by Django 5.2.17 on 2026-09-05 19:43

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0077_cliente_unico_por_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreIfoodIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=64)),
                ('merchant_name', models.CharField(blank=True, default='', max_length=255)),
                ('authorization_code_verifier', models.CharField(blank=True, default='', max_length=255)),
                ('user_code', models.CharField(blank=True, default='', max_length=32)),
                ('user_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_token_encrypted', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=2000)),
                ('refresh_token_encrypted', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=2000)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('conectado', models.BooleanField(default=False)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('ultima_renovacao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ifood', to='stores.store')),
            ],
            options={
                'verbose_name': 'Integração iFood',
                'verbose_name_plural': 'Integrações iFood',
                'db_table': 'store_ifood_integrations',
            },
        ),
    ]
