# Generated by Django 5.2.17 on 2026-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0078_integracao_ifood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cash', 'Dinheiro'), ('bank_transfer', 'Transferência bancária'), ('wallet', 'Carteira digital'), ('voucher', 'Vale-refeição / Vale-alimentação'), ('other', 'Outro')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mercadopago', 'Mercado Pago'), ('pagseguro', 'PagSeguro'), ('pix', 'PIX'), ('pagarme', 'Pagar.me (Stone)'), ('custom', 'Custom')], help_text='Payment gateway provider', max_length=20),
        ),
    ]
