# Generated by Django 5.2.17 on 2026-09-16 13:08

import apps.stores.models.base
from django.core.exceptions import ValidationError
from django.db import migrations, models


def limpar_dominios_invalidos(apps_registry, schema_editor):
    """Zera o que já está gravado e não é hostname.

    Sem isto o validador novo tranca o lojista FORA da própria loja: o
    `custom_domain` inválido viaja em todo PATCH do painel, e ele passaria a
    levar erro ao salvar qualquer campo — cor, horário, o que fosse — por causa
    de um campo que ele nem está editando. Foi exatamente assim que o '' vazio
    derrubou o save de toda loja (ver o comentário em Store.save).

    Ausência de domínio tem uma representação só, e é NULL.
    """
    Store = apps_registry.get_model('stores', 'Store')
    validar = apps.stores.models.base.validar_dominio_proprio
    for store in Store.objects.exclude(custom_domain__isnull=True).exclude(custom_domain=''):
        try:
            validar(store.custom_domain)
        except ValidationError:
            Store.objects.filter(pk=store.pk).update(custom_domain=None)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0081_banners_do_cardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Domínio próprio da loja (ex: cesaladas.com.br)', max_length=255, null=True, unique=True, validators=[apps.stores.models.base.validar_dominio_proprio]),
        ),
        migrations.RunPython(limpar_dominios_invalidos, migrations.RunPython.noop),
    ]
