# Generated by Django 5.2.17 on 2026-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0084_beat_sem_tarefa_fantasma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecashsession',
            name='expected_amount',
            field=models.DecimalField(blank=True, db_column='expected_amount', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RenameField(
            model_name='storecashsession',
            old_name='expected_amount',
            new_name='closing_expected_amount',
        ),
    ]
