# Generated by Django 5.2.17 on 2026-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0086_assinatura_adicionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprintjob',
            name='source',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('manual_reprint', 'Manual Reprint'), ('test', 'Test'), ('etiqueta', 'Etiqueta')], default='order_created', max_length=30),
        ),
        migrations.AlterField(
            model_name='storeprintjob',
            name='template',
            field=models.CharField(choices=[('kitchen_ticket', 'Kitchen Ticket'), ('customer_receipt', 'Customer Receipt'), ('etiqueta_zpl', 'Etiqueta ZPL')], default='kitchen_ticket', max_length=40),
        ),
    ]
