# Generated by Django 5.2.17 on 2026-09-25 17:34

import apps.stores.models.printing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0087_printjob_etiqueta_zpl'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprintagent',
            name='imprime',
            field=models.JSONField(blank=True, default=apps.stores.models.printing._imprime_padrao),
        ),
    ]
