# Generated by Django 5.2.17 on 2026-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0089_storeproduct_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepaymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mercadopago', 'Mercado Pago'), ('pagseguro', 'PagSeguro'), ('pix', 'PIX'), ('pagarme', 'Pagar.me (Stone)'), ('cielo', 'Cielo'), ('custom', 'Custom')], help_text='Payment gateway provider', max_length=20),
        ),
    ]
