# Generated by Django 5.2.17 on 2026-10-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0090_gateway_cielo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDeEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_de_endereco', to='stores.storeorder')),
            ],
            options={
                'verbose_name': 'Alerta de endereço',
                'verbose_name_plural': 'Alertas de endereço',
                'db_table': 'store_alerta_de_endereco',
            },
        ),
    ]
