# Generated by Django 5.2.17 on 2026-10-02 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0091_alerta_de_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaladaSalva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefone', models.CharField(db_index=True, max_length=20)),
                ('client_id', models.UUIDField()),
                ('nome', models.CharField(max_length=40)),
                ('ingredientes', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saladas_salvas', to='stores.store')),
            ],
            options={
                'verbose_name': 'Salada salva',
                'verbose_name_plural': 'Saladas salvas',
                'db_table': 'store_saladas_salvas',
                'ordering': ['-atualizado_em'],
                'constraints': [models.UniqueConstraint(fields=('store', 'telefone', 'client_id'), name='salada_salva_unica_por_aparelho')],
            },
        ),
    ]
