# Generated by Django 5.2.14 on 2026-05-23 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostadoClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('niche', models.CharField(choices=[('restaurant', 'Restaurante'), ('salon', 'Salão'), ('store', 'Loja')], max_length=20)),
                ('tone', models.CharField(choices=[('professional', 'Profissional'), ('casual', 'Descontraído'), ('luxury', 'Luxo')], default='casual', max_length=20)),
                ('brand_colors', models.JSONField(default=list)),
                ('logo_url', models.URLField(blank=True)),
                ('photos', models.JSONField(default=list)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('drive_folder_id', models.CharField(blank=True, max_length=255)),
                ('mp_subscription_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostadoPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('generating', 'Gerando'), ('review', 'Em Revisão'), ('approved', 'Aprovado'), ('delivered', 'Entregue')], default='pending', max_length=20)),
                ('drive_folder_url', models.URLField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='postado.postadoclient')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('client', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PostadoPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_number', models.PositiveSmallIntegerField()),
                ('post_type', models.CharField(choices=[('promo', 'Promoção'), ('product', 'Produto/Serviço'), ('testimonial', 'Depoimento'), ('engagement', 'Engajamento'), ('behind_scenes', 'Bastidor'), ('date', 'Data Comemorativa')], max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255)),
                ('image_prompt', models.TextField(blank=True)),
                ('feed_image_url', models.URLField(blank=True)),
                ('stories_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('generated', 'Gerado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('revision_notes', models.TextField(blank=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='postado.postadopack')),
            ],
            options={
                'ordering': ['post_number'],
                'unique_together': {('pack', 'post_number')},
            },
        ),
    ]
