# Generated by Django 5.2.14 on 2026-05-23 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadoclient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='postadoclient',
            name='whatsapp',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='postadopack',
            name='month',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Format must be YYYY-MM')]),
        ),
    ]
