# Generated by Django 5.2.14 on 2026-05-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postado', '0002_alter_postadoclient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadoclient',
            name='brand_guidelines',
            field=models.TextField(blank=True, help_text='Instruções de voz: "nunca use gírias", "sempre mencione delivery grátis"'),
        ),
        migrations.AddField(
            model_name='postadoclient',
            name='contact_info',
            field=models.JSONField(default=dict, help_text='{"phone": "...", "address": "...", "delivery_link": "..."}'),
        ),
        migrations.AddField(
            model_name='postadoclient',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do negócio — usado pelo LLM pra contextualizar os posts'),
        ),
        migrations.AddField(
            model_name='postadoclient',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='postadoclient',
            name='products',
            field=models.JSONField(default=list, help_text='Lista de produtos/serviços destaque: ["Pizza margherita", "Corte feminino"]'),
        ),
        migrations.AddField(
            model_name='postadoclient',
            name='reference_images',
            field=models.JSONField(default=list, help_text='URLs de fotos reais do negócio'),
        ),
        migrations.AddField(
            model_name='postadoclient',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Ex: "Jovens 25-35, classe A/B, zona sul"', max_length=255),
        ),
    ]
