# Generated by Django 4.2.27 on 2026-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_coupon_deliveryzone_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='scheduled_time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_method',
            field=models.CharField(choices=[('delivery', 'Entrega'), ('pickup', 'Retirada')], default='delivery', max_length=20),
        ),
    ]
