# Generated by Django 5.2.10 on 2026-01-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_delivery_zone_distance_band'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['distance_band', 'min_km', 'zip_code_start'], 'verbose_name': 'Delivery Zone', 'verbose_name_plural': 'Delivery Zones'},
        ),
    ]
