# Generated by Django 4.2.27 on 2026-01-11 04:48
"""
Migration to add store FK and additional fields to Coupon and DeliveryZone.
Works with both PostgreSQL (production) and SQLite (development).
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('ecommerce', '0006_alter_deliveryzone_options'),
    ]

    operations = [
        # Add store FK to Coupon
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='legacy_coupons', 
                to='stores.store',
                help_text='DEPRECATED: Use stores.StoreCoupon instead'
            ),
        ),
        
        # Add store FK to DeliveryZone
        migrations.AddField(
            model_name='deliveryzone',
            name='store',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='legacy_delivery_zones', 
                to='stores.store',
                help_text='DEPRECATED: Use stores.StoreDeliveryZone instead'
            ),
        ),
        
        # Add additional fields to DeliveryZone
        migrations.AddField(
            model_name='deliveryzone',
            name='color',
            field=models.CharField(default='#722F37', max_length=7, help_text='Hex color for map display'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Estimated delivery time in minutes'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='fee_per_km',
            field=models.DecimalField(
                blank=True, 
                null=True, 
                decimal_places=2, 
                max_digits=6, 
                help_text='Additional fee per km (for custom distance zones)'
            ),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='max_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='Maximum travel time in minutes'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='min_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='Minimum travel time in minutes'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon_coordinates',
            field=models.JSONField(
                blank=True, 
                default=list, 
                help_text='GeoJSON coordinates for polygon zones [[lng, lat], ...]'
            ),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='zone_type',
            field=models.CharField(
                max_length=20, 
                default='distance_band',
                choices=[
                    ('distance_band', 'Distance Band'),
                    ('custom_distance', 'Custom Distance Range'),
                    ('zip_range', 'ZIP Code Range'),
                    ('polygon', 'Custom Polygon'),
                    ('time_based', 'Time-based (Isochrone)'),
                ],
                help_text='Type of zone definition'
            ),
        ),
        
        # Alter existing fields
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='distance_band',
            field=models.CharField(
                blank=True, 
                null=True,
                max_length=10, 
                choices=[
                    ('0_2', '0-2 km'), ('2_5', '2-5 km'), ('5_8', '5-8 km'),
                    ('8_12', '8-12 km'), ('12_15', '12-15 km'), ('15_20', '15-20 km'),
                    ('20_30', '20-30 km'), ('30_plus', '30+ km'),
                ]
            ),
        ),
        
        # Update model options
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={
                'ordering': ['store', 'distance_band', 'min_km', 'zip_code_start'], 
                'verbose_name': 'Delivery Zone', 
                'verbose_name_plural': 'Delivery Zones'
            },
        ),
    ]
