# Generated by Django 4.2.27 on 2026-01-11 04:48

from django.db import migrations, models
import django.db.models.deletion


def add_columns_if_not_exist(apps, schema_editor):
    """Add columns using raw SQL with IF NOT EXISTS logic."""
    from django.db import connection
    
    # Define columns to add for deliveryzone
    deliveryzone_columns = [
        ("store_id", "uuid REFERENCES stores_store(id) ON DELETE CASCADE"),
        ("color", "varchar(7) DEFAULT '#722F37'"),
        ("estimated_minutes", "integer DEFAULT 30"),
        ("fee_per_km", "numeric(6,2)"),
        ("max_minutes", "integer"),
        ("min_minutes", "integer"),
        ("polygon_coordinates", "jsonb DEFAULT '[]'::jsonb"),
        ("zone_type", "varchar(20) DEFAULT 'distance_band'"),
    ]
    
    # Define columns to add for coupon
    coupon_columns = [
        ("store_id", "uuid REFERENCES stores_store(id) ON DELETE CASCADE"),
    ]
    
    with connection.cursor() as cursor:
        # Add columns to deliveryzone
        for col_name, col_def in deliveryzone_columns:
            try:
                cursor.execute(f"""
                    ALTER TABLE ecommerce_deliveryzone 
                    ADD COLUMN IF NOT EXISTS {col_name} {col_def}
                """)
            except Exception as e:
                # Column might already exist or other error - continue
                pass
        
        # Add columns to coupon
        for col_name, col_def in coupon_columns:
            try:
                cursor.execute(f"""
                    ALTER TABLE ecommerce_coupon 
                    ADD COLUMN IF NOT EXISTS {col_name} {col_def}
                """)
            except Exception as e:
                pass


def reverse_migration(apps, schema_editor):
    """Reverse migration - do nothing as columns may have data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('ecommerce', '0006_alter_deliveryzone_options'),
    ]

    operations = [
        # Use RunPython to add columns conditionally
        migrations.RunPython(add_columns_if_not_exist, reverse_migration),
        
        # Update model options
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['store', 'distance_band', 'min_km', 'zip_code_start'], 'verbose_name': 'Delivery Zone', 'verbose_name_plural': 'Delivery Zones'},
        ),
    ]
