# Generated by Django 4.2.27 on 2026-01-11 04:48
"""
Migration to add store FK and additional fields to Coupon and DeliveryZone.
Uses ADD COLUMN IF NOT EXISTS for PostgreSQL to be idempotent.
"""

from django.db import migrations, models
import django.db.models.deletion


def add_columns_and_constraints(apps, schema_editor):
    """Add columns and constraints using raw SQL with IF NOT EXISTS for PostgreSQL."""
    from django.db import connection
    
    if connection.vendor != 'postgresql':
        # For SQLite, skip - columns should already exist or will be created by Django
        return
    
    with connection.cursor() as cursor:
        # Coupon columns
        coupon_columns = [
            ("store_id", "uuid REFERENCES stores_store(id) ON DELETE CASCADE"),
        ]
        for col_name, col_def in coupon_columns:
            try:
                cursor.execute(f"ALTER TABLE ecommerce_coupon ADD COLUMN IF NOT EXISTS {col_name} {col_def}")
            except Exception:
                pass
        
        # DeliveryZone columns
        deliveryzone_columns = [
            ("store_id", "uuid REFERENCES stores_store(id) ON DELETE CASCADE"),
            ("color", "varchar(7) DEFAULT '#722F37'"),
            ("estimated_minutes", "integer DEFAULT 30"),
            ("fee_per_km", "numeric(6,2)"),
            ("max_minutes", "integer"),
            ("min_minutes", "integer"),
            ("polygon_coordinates", "jsonb DEFAULT '[]'::jsonb"),
            ("zone_type", "varchar(20) DEFAULT 'distance_band'"),
        ]
        for col_name, col_def in deliveryzone_columns:
            try:
                cursor.execute(f"ALTER TABLE ecommerce_deliveryzone ADD COLUMN IF NOT EXISTS {col_name} {col_def}")
            except Exception:
                pass
        
        # Add unique constraint for coupon (store, code) if not exists
        try:
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'unique_coupon_code_per_store'
                    ) THEN
                        ALTER TABLE ecommerce_coupon 
                        ADD CONSTRAINT unique_coupon_code_per_store UNIQUE (store_id, code);
                    END IF;
                END $$;
            """)
        except Exception:
            pass


def reverse_migration(apps, schema_editor):
    """No-op reverse - preserve data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('ecommerce', '0006_alter_deliveryzone_options'),
    ]

    operations = [
        # Add columns and constraints using raw SQL (idempotent)
        migrations.RunPython(add_columns_and_constraints, reverse_migration),
        
        # State-only operations to register fields with Django ORM
        # These don't touch the database, just update Django's internal state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='coupon',
                    name='store',
                    field=models.ForeignKey(
                        blank=True, 
                        null=True, 
                        on_delete=django.db.models.deletion.CASCADE, 
                        related_name='legacy_coupons', 
                        to='stores.store',
                        help_text='DEPRECATED: Use stores.StoreCoupon instead'
                    ),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='store',
                    field=models.ForeignKey(
                        blank=True, 
                        null=True, 
                        on_delete=django.db.models.deletion.CASCADE, 
                        related_name='legacy_delivery_zones', 
                        to='stores.store',
                        help_text='DEPRECATED: Use stores.StoreDeliveryZone instead'
                    ),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='color',
                    field=models.CharField(default='#722F37', max_length=7, help_text='Hex color for map display'),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='estimated_minutes',
                    field=models.PositiveIntegerField(default=30, help_text='Estimated delivery time in minutes'),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='fee_per_km',
                    field=models.DecimalField(
                        blank=True, 
                        null=True, 
                        decimal_places=2, 
                        max_digits=6, 
                        help_text='Additional fee per km (for custom distance zones)'
                    ),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='max_minutes',
                    field=models.PositiveIntegerField(blank=True, null=True, help_text='Maximum travel time in minutes'),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='min_minutes',
                    field=models.PositiveIntegerField(blank=True, null=True, help_text='Minimum travel time in minutes'),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='polygon_coordinates',
                    field=models.JSONField(
                        blank=True, 
                        default=list, 
                        help_text='GeoJSON coordinates for polygon zones [[lng, lat], ...]'
                    ),
                ),
                migrations.AddField(
                    model_name='deliveryzone',
                    name='zone_type',
                    field=models.CharField(
                        max_length=20, 
                        default='distance_band',
                        choices=[
                            ('distance_band', 'Distance Band'),
                            ('custom_distance', 'Custom Distance Range'),
                            ('zip_range', 'ZIP Code Range'),
                            ('polygon', 'Custom Polygon'),
                            ('time_based', 'Time-based (Isochrone)'),
                        ],
                        help_text='Type of zone definition'
                    ),
                ),
                migrations.AlterField(
                    model_name='coupon',
                    name='code',
                    field=models.CharField(db_index=True, max_length=50),
                ),
                migrations.AlterField(
                    model_name='deliveryzone',
                    name='distance_band',
                    field=models.CharField(
                        blank=True, 
                        null=True,
                        max_length=10, 
                        choices=[
                            ('0_2', '0-2 km'), ('2_5', '2-5 km'), ('5_8', '5-8 km'),
                            ('8_12', '8-12 km'), ('12_15', '12-15 km'), ('15_20', '15-20 km'),
                            ('20_30', '20-30 km'), ('30_plus', '30+ km'),
                        ]
                    ),
                ),
                migrations.AddConstraint(
                    model_name='coupon',
                    constraint=models.UniqueConstraint(
                        fields=['store', 'code'],
                        name='unique_coupon_code_per_store'
                    ),
                ),
            ],
            database_operations=[],  # No DB operations - already handled by RunPython
        ),
        
        # Update model options
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={
                'ordering': ['store', 'distance_band', 'min_km', 'zip_code_start'], 
                'verbose_name': 'Delivery Zone', 
                'verbose_name_plural': 'Delivery Zones'
            },
        ),
    ]
