# Generated by Django 4.2.27 on 2026-01-11 22:25
"""
Migration to update related_names for store FKs.
This is a no-op at database level - only updates Django ORM state.
"""

from django.db import migrations


def noop(apps, schema_editor):
    """No-op - related_name changes don't affect the database."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_migrate_pastita_data'),
        ('ecommerce', '0007_add_store_to_coupon_and_delivery_zone'),
    ]

    operations = [
        # No-op migration - related_name was already set correctly in 0007
        migrations.RunPython(noop, noop),
    ]
