# Generated by Django 4.2.27 on 2026-01-11 22:25

from django.db import migrations, models
import django.db.models.deletion


def update_related_names(apps, schema_editor):
    """Update related names for store FK - this is a no-op at DB level."""
    # The related_name change is only at Django ORM level, not DB level
    pass


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_migrate_pastita_data'),
        ('ecommerce', '0007_add_store_to_coupon_and_delivery_zone'),
    ]

    operations = [
        # Use RunPython instead of AlterField to avoid issues with missing columns
        migrations.RunPython(update_related_names, reverse_migration),
    ]
