# Generated by Django 4.2.27 on 2026-01-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_migrate_pastita_data'),
        ('ecommerce', '0007_add_store_to_coupon_and_delivery_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use stores.StoreCoupon instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_coupons', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='store',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use stores.StoreDeliveryZone instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_delivery_zones', to='stores.store'),
        ),
    ]
