# Generated by Django 4.2.27 on 2026-01-12 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_migrate_pastita_data'),
        ('ecommerce', '0008_alter_coupon_store_alter_deliveryzone_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_coupons', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_delivery_zones', to='stores.store'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_coupon_code_per_store'),
        ),
    ]
