# Generated by Django 4.2.27 on 2026-01-12 02:49
# Modified to use SeparateDatabaseAndState for constraint

from django.db import migrations, models, connection
import django.db.models.deletion


def add_constraint_if_not_exists(apps, schema_editor):
    """Add unique constraint only if it doesn't exist"""
    constraint_name = 'unique_coupon_code_per_store'
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_constraint WHERE conname = %s
        """, [constraint_name])
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE ecommerce_coupon 
                ADD CONSTRAINT unique_coupon_code_per_store 
                UNIQUE (store_id, code)
            """)


def remove_constraint_if_exists(apps, schema_editor):
    """Remove constraint if it exists (for rollback)"""
    constraint_name = 'unique_coupon_code_per_store'
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_constraint WHERE conname = %s
        """, [constraint_name])
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE ecommerce_coupon 
                DROP CONSTRAINT unique_coupon_code_per_store
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_migrate_pastita_data'),
        ('ecommerce', '0008_alter_coupon_store_alter_deliveryzone_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_coupons', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_delivery_zones', to='stores.store'),
        ),
        # Use SeparateDatabaseAndState to:
        # 1. Run idempotent database operations via RunPython
        # 2. Update Django's state to know the constraint exists
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_constraint_if_not_exists, remove_constraint_if_exists),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='coupon',
                    constraint=models.UniqueConstraint(
                        fields=['store', 'code'],
                        name='unique_coupon_code_per_store'
                    ),
                ),
            ],
        ),
    ]
