# Generated by Django 4.2.27 on 2026-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_coupon_store_alter_deliveryzone_store_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_coupon_code_per_store'),
        ),
    ]
