# Generated by Django 4.2.28 on 2026-02-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('auto', 'Automated'), ('human', 'Human Agent'), ('hybrid', 'Hybrid')], default='auto', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('agent_session_id', models.CharField(blank=True, help_text='ID da sessão do agente para memória', max_length=100)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_agent_message_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_notes', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Conversation Note',
                'verbose_name_plural': 'Conversation Notes',
                'db_table': 'conversation_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
