# Generated by Django 4.2.28 on 2026-02-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
        ('agents', '0002_add_fields'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp.whatsappaccount'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_agent',
            field=models.ForeignKey(blank=True, help_text='Agente IA vinculado a esta conversa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['account', 'status', '-last_message_at'], name='conversatio_account_47e0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_agent', 'status'], name='conversatio_assigne_ffabd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('account', 'phone_number')},
        ),
    ]
