# Generated by Django 6.0.1 on 2026-01-09 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('whatsapp', '0001_initial'),
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp.whatsappaccount'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='agents.agent', help_text='Agente IA vinculado a esta conversa'),
        ),
        migrations.AddField(
            model_name='conversationnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationnote',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='conversations.conversation'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['account', 'status', '-last_message_at'], name='conversatio_account_47e0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_agent', 'status'], name='conversatio_assigne_ffabd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('account', 'phone_number')},
        ),
    ]
