# Generated by Django 4.2.27 on 2026-02-10 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # This migration duplicated operations contained in 0002_add_fields.
    # Convert it into a no-op merge entry that depends on the true 0002_add_fields
    # to ensure the migration graph applies operations only once.
    initial = False

    dependencies = [
        ('conversations', '0001_initial'),
        ('conversations', '0002_add_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
