# Generated by Django 4.2.28 on 2026-02-09 01:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_owner', models.CharField(choices=[('bot', 'Bot (IA)'), ('human', 'Atendente Humano')], default='bot', max_length=10, verbose_name='Dono Atual')),
                ('requested_owner', models.CharField(blank=True, choices=[('bot', 'Bot (IA)'), ('human', 'Atendente Humano')], max_length=10, null=True, verbose_name='Dono Solicitado')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('pending', 'Pendente'), ('completed', 'Completo'), ('expired', 'Expirado')], default='active', max_length=20, verbose_name='Status')),
                ('human_agent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Atendente')),
                ('human_agent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Atendente')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='conversations.conversation', verbose_name='Conversação')),
            ],
            options={
                'verbose_name': 'Handover de Conversa',
                'verbose_name_plural': 'Handovers de Conversas',
                'db_table': 'conversation_handovers',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['conversation', 'status'], name='conversatio_convers_d580a3_idx'), models.Index(fields=['current_owner', 'status'], name='conversatio_current_7fee96_idx'), models.Index(fields=['human_agent_id', 'status'], name='conversatio_human_a_d841bf_idx'), models.Index(fields=['expires_at'], name='conversatio_expires_b2138e_idx')],
            },
        ),
    ]
