# Generated by Django 4.2.28 on 2026-03-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationHandover',
        ),
    ]
